/*
 Platform.js <https://mths.be/platform>
 Copyright 2014-2018 Benjamin Tan <https://bnjmnt4n.now.sh/>
 Copyright 2011-2013 John-David Dalton
 Available under MIT license <https://mths.be/mit>
*/
(function(){var a="undefined"!==typeof window&&"undefined"!==typeof window.document?window.document:{},g="undefined"!==typeof module&&module.exports,e=function(){for(var d,f=["requestFullscreen exitFullscreen fullscreenElement fullscreenEnabled fullscreenchange fullscreenerror".split(" "),"webkitRequestFullscreen webkitExitFullscreen webkitFullscreenElement webkitFullscreenEnabled webkitfullscreenchange webkitfullscreenerror".split(" "),"webkitRequestFullScreen webkitCancelFullScreen webkitCurrentFullScreenElement webkitCancelFullScreen webkitfullscreenchange webkitfullscreenerror".split(" "),
"mozRequestFullScreen mozCancelFullScreen mozFullScreenElement mozFullScreenEnabled mozfullscreenchange mozfullscreenerror".split(" "),"msRequestFullscreen msExitFullscreen msFullscreenElement msFullscreenEnabled MSFullscreenChange MSFullscreenError".split(" ")],b=0,n=f.length,c={};b<n;b++)if((d=f[b])&&d[1]in a){for(b=0;b<d.length;b++)c[f[0][b]]=d[b];return c}return!1}(),k={change:e.fullscreenchange,error:e.fullscreenerror},h={request:function(d){return new Promise(function(f,b){var n=function(){this.off("change",
n);f()}.bind(this);this.on("change",n);d=d||a.documentElement;Promise.resolve(d[e.requestFullscreen]())["catch"](b)}.bind(this))},exit:function(){return new Promise(function(d,f){if(this.isFullscreen){var b=function(){this.off("change",b);d()}.bind(this);this.on("change",b);Promise.resolve(a[e.exitFullscreen]())["catch"](f)}else d()}.bind(this))},toggle:function(d){return this.isFullscreen?this.exit():this.request(d)},onchange:function(d){this.on("change",d)},onerror:function(d){this.on("error",d)},
on:function(d,f){var b=k[d];b&&a.addEventListener(b,f,!1)},off:function(d,f){var b=k[d];b&&a.removeEventListener(b,f,!1)},raw:e};e?(Object.defineProperties(h,{isFullscreen:{get:function(){return!!a[e.fullscreenElement]}},element:{enumerable:!0,get:function(){return a[e.fullscreenElement]}},isEnabled:{enumerable:!0,get:function(){return!!a[e.fullscreenEnabled]}}}),g?module.exports=h:window.screenfull=h):g?module.exports={isEnabled:!1}:window.screenfull={isEnabled:!1}})();
(function(){function a(p){p=String(p);return p.charAt(0).toUpperCase()+p.slice(1)}function g(p,F){var z=-1,w=p?p.length:0;if("number"==typeof w&&-1<w&&w<=r)for(;++z<w;)F(p[z],z,p);else k(p,F)}function e(p){p=String(p).replace(/^ +| +$/g,"");return/^(?:webOS|i(?:OS|P))/.test(p)?p:a(p)}function k(p,F){for(var z in p)y.call(p,z)&&F(p[z],z,p)}function h(p){return null==p?a(p):D.call(p).slice(8,-1)}function d(p,F){var z=null!=p?typeof p[F]:"number";return!/^(?:boolean|number|string|undefined)$/.test(z)&&
("object"==z?!!p[F]:!0)}function f(p){return String(p).replace(/([ -])(?!$)/g,"$1?")}function b(p,F){var z=null;g(p,function(w,v){z=F(z,w,v,p)});return z}function n(p){function F(S){return b(S,function(N,L){var U=L.pattern||f(L);!N&&(N=RegExp("\\b"+U+" *\\d+[.\\w_]*","i").exec(p)||RegExp("\\b"+U+" *\\w+-[\\w]*","i").exec(p)||RegExp("\\b"+U+"(?:; *(?:[a-z]+[_-])?[a-z]+\\d+|[^ ();-]*)","i").exec(p))&&((N=String(L.label&&!RegExp(U,"i").test(L.label)?L.label:N).split("/"))[1]&&!/[\d.]+/.test(N[0])&&(N[0]+=
" "+N[1]),L=L.label||L,N=e(N[0].replace(RegExp(U,"i"),L).replace(RegExp("; *(?:"+L+"[_-])?","i")," ").replace(RegExp("("+L+")[-_.]?(\\w)","i"),"$1 $2")));return N})}function z(S){return b(S,function(N,L){return N||(RegExp(L+"(?:-[\\d.]+/|(?: for [\\w-]+)?[ /-])([\\d.]+[^ ();/_-]*)","i").exec(p)||0)[1]||null})}var w=t,v=p&&"object"==typeof p&&"String"!=h(p);v&&(w=p,p=null);var H=w.navigator||{},x=H.userAgent||"";p||(p=x);var P=v?!!H.likeChrome:/\bChrome\b/.test(p)&&!/internal|\n/i.test(D.toString()),
O=v?"Object":"ScriptBridgingProxyObject",Q=v?"Object":"Environment",I=v&&w.java?"JavaPackage":h(w.java),T=v?"Object":"RuntimeObject";Q=(I=/\bJava/.test(I)&&w.java)&&h(w.environment)==Q;var R=I?"a":"\u03b1",W=I?"b":"\u03b2",B=w.document||{},G=w.operamini||w.opera,M=q.test(M=v&&G?G["[[Class]]"]:h(G))?M:G=null,l,Z=p;v=[];var aa=null,Y=p==x;x=Y&&G&&"function"==typeof G.version&&G.version();var J=function(S){return b(S,function(N,L){return N||RegExp("\\b"+(L.pattern||f(L))+"\\b","i").exec(p)&&(L.label||
L)})}([{label:"EdgeHTML",pattern:"Edge"},"Trident",{label:"WebKit",pattern:"AppleWebKit"},"iCab","Presto","NetFront","Tasman","KHTML","Gecko"]),C=function(S){return b(S,function(N,L){return N||RegExp("\\b"+(L.pattern||f(L))+"\\b","i").exec(p)&&(L.label||L)})}(["Adobe AIR","Arora","Avant Browser","Breach","Camino","Electron","Epiphany","Fennec","Flock","Galeon","GreenBrowser","iCab","Iceweasel","K-Meleon","Konqueror","Lunascape","Maxthon",{label:"Microsoft Edge",pattern:"Edge"},"Midori","Nook Browser",
"PaleMoon","PhantomJS","Raven","Rekonq","RockMelt",{label:"Samsung Internet",pattern:"SamsungBrowser"},"SeaMonkey",{label:"Silk",pattern:"(?:Cloud9|Silk-Accelerated)"},"Sleipnir","SlimBrowser",{label:"SRWare Iron",pattern:"Iron"},"Sunrise","Swiftfox","Waterfox","WebPositive","Opera Mini",{label:"Opera Mini",pattern:"OPiOS"},"Opera",{label:"Opera",pattern:"OPR"},"Chrome",{label:"Chrome Mobile",pattern:"(?:CriOS|CrMo)"},{label:"Firefox",pattern:"(?:Firefox|Minefield)"},{label:"Firefox for iOS",pattern:"FxiOS"},
{label:"IE",pattern:"IEMobile"},{label:"IE",pattern:"MSIE"},"Safari"]),K=F([{label:"BlackBerry",pattern:"BB10"},"BlackBerry",{label:"Galaxy S",pattern:"GT-I9000"},{label:"Galaxy S2",pattern:"GT-I9100"},{label:"Galaxy S3",pattern:"GT-I9300"},{label:"Galaxy S4",pattern:"GT-I9500"},{label:"Galaxy S5",pattern:"SM-G900"},{label:"Galaxy S6",pattern:"SM-G920"},{label:"Galaxy S6 Edge",pattern:"SM-G925"},{label:"Galaxy S7",pattern:"SM-G930"},{label:"Galaxy S7 Edge",pattern:"SM-G935"},"Google TV","Lumia","iPad",
"iPod","iPhone","Kindle",{label:"Kindle Fire",pattern:"(?:Cloud9|Silk-Accelerated)"},"Nexus","Nook","PlayBook","PlayStation Vita","PlayStation","TouchPad","Transformer",{label:"Wii U",pattern:"WiiU"},"Wii","Xbox One",{label:"Xbox 360",pattern:"Xbox"},"Xoom"]),V=function(S){return b(S,function(N,L,U){return N||(L[K]||L[/^[a-z]+(?: +[a-z]+\b)*/i.exec(K)]||RegExp("\\b"+f(U)+"(?:\\b|\\w*\\d)","i").exec(p))&&U})}({Apple:{iPad:1,iPhone:1,iPod:1},Archos:{},Amazon:{Kindle:1,"Kindle Fire":1},Asus:{Transformer:1},
"Barnes & Noble":{Nook:1},BlackBerry:{PlayBook:1},Google:{"Google TV":1,Nexus:1},HP:{TouchPad:1},HTC:{},LG:{},Microsoft:{Xbox:1,"Xbox One":1},Motorola:{Xoom:1},Nintendo:{"Wii U":1,Wii:1},Nokia:{Lumia:1},Samsung:{"Galaxy S":1,"Galaxy S2":1,"Galaxy S3":1,"Galaxy S4":1},Sony:{PlayStation:1,"PlayStation Vita":1}}),E=function(S){return b(S,function(N,L){var U=L.pattern||f(L);if(!N&&(N=RegExp("\\b"+U+"(?:/[\\d.]+|[ \\w.]*)","i").exec(p))){var X=N,ba=L.label||L,ca={"10.0":"10","6.4":"10 Technical Preview",
"6.3":"8.1","6.2":"8","6.1":"Server 2008 R2 / 7","6.0":"Server 2008 / Vista","5.2":"Server 2003 / XP 64-bit","5.1":"XP","5.01":"2000 SP1","5.0":"2000","4.0":"NT","4.90":"ME"};U&&ba&&/^Win/i.test(X)&&!/^Windows Phone /i.test(X)&&(ca=ca[/[\d.]+$/.exec(X)])&&(X="Windows "+ca);X=String(X);U&&ba&&(X=X.replace(RegExp(U,"i"),ba));N=X=e(X.replace(/ ce$/i," CE").replace(/\bhpw/i,"web").replace(/\bMacintosh\b/,"Mac OS").replace(/_PowerPC\b/i," OS").replace(/\b(OS X) [^ \d]+/i,"$1").replace(/\bMac (OS X)\b/,
"$1").replace(/\/(\d)/," $1").replace(/_/g,".").replace(/(?: BePC|[ .]*fc[ \d.]+)$/i,"").replace(/\bx86\.64\b/gi,"x86_64").replace(/\b(Windows Phone) OS\b/,"$1").replace(/\b(Chrome OS \w+) [\d.]+\b/,"$1").split(" on ")[0])}return N})}(["Windows Phone","Android","CentOS",{label:"Chrome OS",pattern:"CrOS"},"Debian","Fedora","FreeBSD","Gentoo","Haiku","Kubuntu","Linux Mint","OpenBSD","Red Hat","SuSE","Ubuntu","Xubuntu","Cygwin","Symbian OS","hpwOS","webOS ","webOS","Tablet OS","Tizen","Linux","Mac OS X",
"Macintosh","Mac","Windows 98;","Windows "]);J&&(J=[J]);V&&!K&&(K=F([V]));if(l=/\bGoogle TV\b/.exec(K))K=l[0];/\bSimulator\b/i.test(p)&&(K=(K?K+" ":"")+"Simulator");"Opera Mini"==C&&/\bOPiOS\b/.test(p)&&v.push("running in Turbo/Uncompressed mode");"IE"==C&&/\blike iPhone OS\b/.test(p)?(l=n(p.replace(/like iPhone OS/,"")),V=l.manufacturer,K=l.product):/^iP/.test(K)?(C||(C="Safari"),E="iOS"+((l=/ OS ([\d_]+)/i.exec(p))?" "+l[1].replace(/_/g,"."):"")):"Konqueror"!=C||/buntu/i.test(E)?V&&"Google"!=V&&
(/Chrome/.test(C)&&!/\bMobile Safari\b/i.test(p)||/\bVita\b/.test(K))||/\bAndroid\b/.test(E)&&/^Chrome/.test(C)&&/\bVersion\//i.test(p)?(C="Android Browser",E=/\bAndroid\b/.test(E)?E:"Android"):"Silk"==C?(/\bMobi/i.test(p)||(E="Android",v.unshift("desktop mode")),/Accelerated *= *true/i.test(p)&&v.unshift("accelerated")):"PaleMoon"==C&&(l=/\bFirefox\/([\d.]+)\b/.exec(p))?v.push("identifying as Firefox "+l[1]):"Firefox"==C&&(l=/\b(Mobile|Tablet|TV)\b/i.exec(p))?(E||(E="Firefox OS"),K||(K=l[1])):!C||
(l=!/\bMinefield\b/i.test(p)&&/\b(?:Firefox|Safari)\b/.exec(C))?(C&&!K&&/[\/,]|^[^(]+?\)/.test(p.slice(p.indexOf(l+"/")+8))&&(C=null),(l=K||V||E)&&(K||V||/\b(?:Android|Symbian OS|Tablet OS|webOS)\b/.test(E))&&(C=/[a-z]+(?: Hat)?/i.exec(/\bAndroid\b/.test(E)?E:l)+" Browser")):"Electron"==C&&(l=(/\bChrome\/([\d.]+)\b/.exec(p)||0)[1])&&v.push("Chromium "+l):E="Kubuntu";x||(x=z(["(?:Cloud9|CriOS|CrMo|Edge|FxiOS|IEMobile|Iron|Opera ?Mini|OPiOS|OPR|Raven|SamsungBrowser|Silk(?!/[\\d.]+$))","Version",f(C),
"(?:Firefox|Minefield|NetFront)"]));if(l="iCab"==J&&3<parseFloat(x)&&"WebKit"||/\bOpera\b/.test(C)&&(/\bOPR\b/.test(p)?"Blink":"Presto")||/\b(?:Midori|Nook|Safari)\b/i.test(p)&&!/^(?:Trident|EdgeHTML)$/.test(J)&&"WebKit"||!J&&/\bMSIE\b/i.test(p)&&("Mac OS"==E?"Tasman":"Trident")||"WebKit"==J&&/\bPlayStation\b(?! Vita\b)/i.test(C)&&"NetFront")J=[l];"IE"==C&&(l=(/; *(?:XBLWP|ZuneWP)(\d+)/i.exec(p)||0)[1])?(C+=" Mobile",E="Windows Phone "+(/\+$/.test(l)?l:l+".x"),v.unshift("desktop mode")):/\bWPDesktop\b/i.test(p)?
(C="IE Mobile",E="Windows Phone 8.x",v.unshift("desktop mode"),x||(x=(/\brv:([\d.]+)/.exec(p)||0)[1])):"IE"!=C&&"Trident"==J&&(l=/\brv:([\d.]+)/.exec(p))&&(C&&v.push("identifying as "+C+(x?" "+x:"")),C="IE",x=l[1]);if(Y){if(d(w,"global"))if(I&&(l=I.lang.System,Z=l.getProperty("os.arch"),E=E||l.getProperty("os.name")+" "+l.getProperty("os.version")),Q){try{x=w.require("ringo/engine").version.join("."),C="RingoJS"}catch(S){(l=w.system)&&l.global.system==w.system&&(C="Narwhal",E||(E=l[0].os||null))}C||
(C="Rhino")}else"object"==typeof w.process&&!w.process.browser&&(l=w.process)&&("object"==typeof l.versions&&("string"==typeof l.versions.electron?(v.push("Node "+l.versions.node),C="Electron",x=l.versions.electron):"string"==typeof l.versions.nw&&(v.push("Chromium "+x,"Node "+l.versions.node),C="NW.js",x=l.versions.nw)),C||(C="Node.js",Z=l.arch,E=l.platform,x=(x=/[\d.]+/.exec(l.version))?x[0]:null));else h(l=w.runtime)==O?(C="Adobe AIR",E=l.flash.system.Capabilities.os):h(l=w.phantom)==T?(C="PhantomJS",
x=(l=l.version||null)&&l.major+"."+l.minor+"."+l.patch):"number"==typeof B.documentMode&&(l=/\bTrident\/(\d+)/i.exec(p))?(x=[x,B.documentMode],(l=+l[1]+4)!=x[1]&&(v.push("IE "+x[1]+" mode"),J&&(J[1]=""),x[1]=l),x="IE"==C?String(x[1].toFixed(1)):x[0]):"number"==typeof B.documentMode&&/^(?:Chrome|Firefox)\b/.test(C)&&(v.push("masking as "+C+" "+x),C="IE",x="11.0",J=["Trident"],E="Windows");E=E&&e(E)}x&&(l=/(?:[ab]|dp|pre|[ab]\d+pre)(?:\d+\+?)?$/i.exec(x)||/(?:alpha|beta)(?: ?\d)?/i.exec(p+";"+(Y&&H.appMinorVersion))||
/\bMinefield\b/i.test(p)&&"a")&&(aa=/b/i.test(l)?"beta":"alpha",x=x.replace(RegExp(l+"\\+?$"),"")+("beta"==aa?W:R)+(/\d+\+?/.exec(l)||""));if("Fennec"==C||"Firefox"==C&&/\b(?:Android|Firefox OS)\b/.test(E))C="Firefox Mobile";else if("Maxthon"==C&&x)x=x.replace(/\.[\d.]+/,".x");else if(/\bXbox\b/i.test(K))"Xbox 360"==K&&(E=null),"Xbox 360"==K&&/\bIEMobile\b/.test(p)&&v.unshift("mobile mode");else if(!/^(?:Chrome|IE|Opera)$/.test(C)&&(!C||K||/Browser|Mobi/.test(C))||"Windows CE"!=E&&!/Mobi/i.test(p))if("IE"==
C&&Y)try{null===w.external&&v.unshift("platform preview")}catch(S){v.unshift("embedded")}else(/\bBlackBerry\b/.test(K)||/\bBB10\b/.test(p))&&(l=(RegExp(K.replace(/ +/g," *")+"/([.\\d]+)","i").exec(p)||0)[1]||x)?(l=[l,/BB10/.test(p)],E=(l[1]?(K=null,V="BlackBerry"):"Device Software")+" "+l[0],x=null):this!=k&&"Wii"!=K&&(Y&&G||/Opera/.test(C)&&/\b(?:MSIE|Firefox)\b/i.test(p)||"Firefox"==C&&/\bOS X (?:\d+\.){2,}/.test(E)||"IE"==C&&(E&&!/^Win/.test(E)&&5.5<x||/\bWindows XP\b/.test(E)&&8<x||8==x&&!/\bTrident\b/.test(p)))&&
!q.test(l=n.call(k,p.replace(q,"")+";"))&&l.name&&(l="ing as "+l.name+((l=l.version)?" "+l:""),q.test(C)?(/\bIE\b/.test(l)&&"Mac OS"==E&&(E=null),l="identify"+l):(l="mask"+l,C=M?e(M.replace(/([a-z])([A-Z])/g,"$1 $2")):"Opera",/\bIE\b/.test(l)&&(E=null),Y||(x=null)),J=["Presto"],v.push(l));else C+=" Mobile";if(l=(/\bAppleWebKit\/([\d.]+\+?)/i.exec(p)||0)[1]){l=[parseFloat(l.replace(/\.(\d)$/,".0$1")),l];if("Safari"==C&&"+"==l[1].slice(-1))C="WebKit Nightly",aa="alpha",x=l[1].slice(0,-1);else if(x==
l[1]||x==(l[2]=(/\bSafari\/([\d.]+\+?)/i.exec(p)||0)[1]))x=null;l[1]=(/\bChrome\/([\d.]+)/i.exec(p)||0)[1];537.36==l[0]&&537.36==l[2]&&28<=parseFloat(l[1])&&"WebKit"==J&&(J=["Blink"]);Y&&(P||l[1])?(J&&(J[1]="like Chrome"),l=l[1]||(l=l[0],530>l?1:532>l?2:532.05>l?3:533>l?4:534.03>l?5:534.07>l?6:534.1>l?7:534.13>l?8:534.16>l?9:534.24>l?10:534.3>l?11:535.01>l?12:535.02>l?"13+":535.07>l?15:535.11>l?16:535.19>l?17:536.05>l?18:536.1>l?19:537.01>l?20:537.11>l?"21+":537.13>l?23:537.18>l?24:537.24>l?25:537.36>
l?26:"Blink"!=J?"27":"28")):(J&&(J[1]="like Safari"),l=(l=l[0],400>l?1:500>l?2:526>l?3:533>l?4:534>l?"4+":535>l?5:537>l?6:538>l?7:601>l?8:"8"));J&&(J[1]+=" "+(l+="number"==typeof l?".x":/[.+]/.test(l)?"":"+"));"Safari"==C&&(!x||45<parseInt(x))&&(x=l)}"Opera"==C&&(l=/\bzbov|zvav$/.exec(E))?(C+=" ",v.unshift("desktop mode"),"zvav"==l?(C+="Mini",x=null):C+="Mobile",E=E.replace(RegExp(" *"+l+"$"),"")):"Safari"==C&&/\bChrome\b/.exec(J&&J[1])&&(v.unshift("desktop mode"),C="Chrome Mobile",x=null,/\bOS X\b/.test(E)?
(V="Apple",E="iOS 4.3+"):E=null);x&&0==x.indexOf(l=/[\d.]+$/.exec(E))&&-1<p.indexOf("/"+l+"-")&&(E=String(E.replace(l,"")).replace(/^ +| +$/g,""));J&&!/\b(?:Avant|Nook)\b/.test(C)&&(/Browser|Lunascape|Maxthon/.test(C)||"Safari"!=C&&/^iOS/.test(E)&&/\bSafari\b/.test(J[1])||/^(?:Adobe|Arora|Breach|Midori|Opera|Phantom|Rekonq|Rock|Samsung Internet|Sleipnir|Web)/.test(C)&&J[1])&&(l=J[J.length-1])&&v.push(l);v.length&&(v=["("+v.join("; ")+")"]);V&&K&&0>K.indexOf(V)&&v.push("on "+V);K&&v.push((/^on /.test(v[v.length-
1])?"":"on ")+K);if(E){var da=(l=/ ([\d.+]+)$/.exec(E))&&"/"==E.charAt(E.length-l[0].length-1);E={architecture:32,family:l&&!da?E.replace(l[0],""):E,version:l?l[1]:null,toString:function(){var S=this.version;return this.family+(S&&!da?" "+S:"")+(64==this.architecture?" 64-bit":"")}}}(l=/\b(?:AMD|IA|Win|WOW|x86_|x)64\b/i.exec(Z))&&!/\bi686\b/i.test(Z)?(E&&(E.architecture=64,E.family=E.family.replace(RegExp(" *"+l),"")),C&&(/\bWOW64\b/i.test(p)||Y&&/\w(?:86|32)$/.test(H.cpuClass||H.platform)&&!/\bWin64; x64\b/i.test(p))&&
v.unshift("32-bit")):E&&/^OS X/.test(E.family)&&"Chrome"==C&&39<=parseFloat(x)&&(E.architecture=64);p||(p=null);w={};w.description=p;w.layout=J&&J[0];w.manufacturer=V;w.name=C;w.prerelease=aa;w.product=K;w.ua=p;w.version=C&&x;w.os=E||{architecture:null,family:null,version:null,toString:function(){return"null"}};w.parse=n;w.toString=function(){return this.description||""};w.version&&v.unshift(x);w.name&&v.unshift(C);E&&C&&(E!=String(E).split(" ")[0]||E!=C.split(" ")[0]&&!K)&&v.push(K?"("+E+")":"on "+
E);v.length&&(w.description=v.join(" "));return w}var c={"function":!0,object:!0},t=c[typeof window]&&window||this,u=c[typeof exports]&&exports;c=c[typeof module]&&module&&!module.nodeType&&module;var m=u&&c&&"object"==typeof global&&global;!m||m.global!==m&&m.window!==m&&m.self!==m||(t=m);var r=Math.pow(2,53)-1,q=/\bOpera/;m=Object.prototype;var y=m.hasOwnProperty,D=m.toString,A=n();"function"==typeof define&&"object"==typeof define.amd&&define.amd?(t.platform=A,define(function(){return A})):u&&
c?k(A,function(p,F){u[F]=p}):t.platform=A}).call(this);
function buildIOSMeta(){for(var a=[{name:"viewport",content:"width=device-width, height=device-height, initial-scale=1, minimum-scale=1, maximum-scale=1, user-scalable=no"},{name:"apple-mobile-web-app-capable",content:"yes"},{name:"apple-mobile-web-app-status-bar-style",content:"black"}],g=0;g<a.length;g++){var e=document.createElement("meta");e.name=a[g].name;e.content=a[g].content;var k=window.document.head.querySelector('meta[name="'+e.name+'"]');k&&k.parentNode.removeChild(k);window.document.head.appendChild(e)}}
function hideIOSFullscreenPanel(){document.querySelector(".xxx-ios-fullscreen-message").style.display="none";document.querySelector(".xxx-ios-fullscreen-scroll").style.display="none";document.querySelector(".xxx-game-iframe-full").classList.remove("xxx-game-iframe-iphone-se")}function buildIOSFullscreenPanel(){document.body.insertAdjacentHTML("beforeend",'<div class="xxx-ios-fullscreen-message"><div class="xxx-ios-fullscreen-swipe"></div></div><div class="xxx-ios-fullscreen-scroll"></div>')}
function showIOSFullscreenPanel(){document.querySelector(".xxx-ios-fullscreen-message").style.display="none";document.querySelector(".xxx-ios-fullscreen-scroll").style.display="none"}
function __iosResize(){window.scrollTo(0,0);console.log(window.devicePixelRatio);console.log(window.innerWidth);console.log(window.innerHeight);if("iPhone"===platform.product)switch(window.devicePixelRatio){case 2:switch(window.innerWidth){case 568:320!==window.innerHeight&&document.querySelector(".xxx-game-iframe-full").classList.add("xxx-game-iframe-iphone-se");break;case 667:375===window.innerHeight?hideIOSFullscreenPanel():showIOSFullscreenPanel();break;case 808:414===window.innerHeight?hideIOSFullscreenPanel():
showIOSFullscreenPanel();break;default:hideIOSFullscreenPanel()}break;case 3:switch(window.innerWidth){case 736:414===window.innerHeight?hideIOSFullscreenPanel():showIOSFullscreenPanel();break;case 724:375===window.innerHeight?hideIOSFullscreenPanel():showIOSFullscreenPanel();break;case 808:414===window.innerHeight?hideIOSFullscreenPanel():showIOSFullscreenPanel();break;default:hideIOSFullscreenPanel()}break;default:hideIOSFullscreenPanel()}}
function iosResize(){__iosResize();setTimeout(function(){__iosResize()},500)}function iosInIframe(){try{return window.self!==window.top}catch(a){return!0}}function isIOSLessThen13(){var a=platform.os,g=a.family.toLowerCase();a=parseFloat(a.version);return"ios"===g&&13>a?!0:!1}document.addEventListener("DOMContentLoaded",function(){platform&&"iPhone"===platform.product&&"safari"===platform.name.toLowerCase()&&isIOSLessThen13()&&!iosInIframe()&&(buildIOSFullscreenPanel(),buildIOSMeta())});
window.addEventListener("resize",function(a){platform&&"iPhone"===platform.product&&"safari"===platform.name.toLowerCase()&&isIOSLessThen13()&&!iosInIframe()&&iosResize()});
var s_iScaleFactor=1,s_oCanvasLeft,s_oCanvasTop,s_bIsIphone,s_bFocus=!0,browserName=function(a){switch(!0){case -1<a.indexOf("edge"):return"MS Edge";case -1<a.indexOf("edg/"):return"Edge ( chromium based)";case -1<a.indexOf("opr")&&!!window.opr:return"Opera";case -1<a.indexOf("chrome")&&!!window.chrome:return"Chrome";case -1<a.indexOf("trident"):return"MS IE";case -1<a.indexOf("firefox"):return"Mozilla Firefox";case -1<a.indexOf("safari"):return"Safari";default:return"other"}}(window.navigator.userAgent.toLowerCase());
window.addEventListener("resize",function(a){sizeHandler()},!0);function trace(a){console.log(a)}function isIpad(){var a=-1!==navigator.userAgent.toLowerCase().indexOf("ipad");return!a&&navigator.userAgent.match(/Mac/)&&navigator.maxTouchPoints&&2<navigator.maxTouchPoints?!0:a}
function isMobile(){return isIpad()?!0:navigator.userAgent.match(/Android/i)||navigator.userAgent.match(/webOS/i)||navigator.userAgent.match(/iPhone/i)||navigator.userAgent.match(/iPad/i)||navigator.userAgent.match(/iPod/i)||navigator.userAgent.match(/BlackBerry/i)||navigator.userAgent.match(/Windows Phone/i)?!0:!1}
function isIOS(){for(var a="iPad Simulator;iPhone Simulator;iPod Simulator;iPad;iPhone;iPod".split(";");a.length;)if(navigator.platform===a.pop())return s_bIsIphone=!0;return s_bIsIphone=!1}
function getSize(a){var g=a.toLowerCase(),e=window.document,k=e.documentElement;if(void 0===window["inner"+a])a=k["client"+a];else if(window["inner"+a]!=k["client"+a]){var h=e.createElement("body");h.id="vpw-test-b";h.style.cssText="overflow:scroll";var d=e.createElement("div");d.id="vpw-test-d";d.style.cssText="position:absolute;top:-1000px";d.innerHTML="<style>@media("+g+":"+k["client"+a]+"px){body#vpw-test-b div#vpw-test-d{"+g+":7px!important}}</style>";h.appendChild(d);k.insertBefore(h,e.head);
a=7==d["offset"+a]?k["client"+a]:window["inner"+a];k.removeChild(h)}else a=window["inner"+a];return a}window.addEventListener("orientationchange",onOrientationChange);function onOrientationChange(){window.matchMedia("(orientation: portrait)").matches&&sizeHandler();window.matchMedia("(orientation: landscape)").matches&&sizeHandler()}function getIOSWindowHeight(){return document.documentElement.clientWidth/window.innerWidth*window.innerHeight}
function getHeightOfIOSToolbars(){var a=(0===window.orientation?screen.height:screen.width)-getIOSWindowHeight();return 1<a?a:0}
function sizeHandler(){window.scrollTo(0,1);if(document.querySelector("#canvas")){var a=null!==platform.name&&"safari"===platform.name.toLowerCase()?getIOSWindowHeight():getSize("Height");var g=getSize("Width");s_bFocus&&_checkOrientation(g,a);var e=Math.min(a/CANVAS_HEIGHT,g/CANVAS_WIDTH),k=Math.round(CANVAS_WIDTH*e);e=Math.round(CANVAS_HEIGHT*e);if(e<a){var h=a-e;e+=h;k+=CANVAS_WIDTH/CANVAS_HEIGHT*h}else k<g&&(h=g-k,k+=h,e+=CANVAS_HEIGHT/CANVAS_WIDTH*h);h=a/2-e/2;var d=g/2-k/2,f=CANVAS_WIDTH/k;
if(d*f<-EDGEBOARD_X||h*f<-EDGEBOARD_Y)e=Math.min(a/(CANVAS_HEIGHT-2*EDGEBOARD_Y),g/(CANVAS_WIDTH-2*EDGEBOARD_X)),k=Math.round(CANVAS_WIDTH*e),e=Math.round(CANVAS_HEIGHT*e),h=(a-e)/2,d=(g-k)/2,f=CANVAS_WIDTH/k;s_iOffsetX=-1*d*f;s_iOffsetY=-1*h*f;0<=h&&(s_iOffsetY=0);0<=d&&(s_iOffsetX=0);null!==s_oGame&&s_oGame.refreshButtonPos();null!==s_oMenu&&s_oMenu.refreshButtonPos();null!==s_oLevelMenu&&s_oLevelMenu.refreshButtonPos();s_bMobile?(document.querySelector("#canvas").style.width=k+"px",document.querySelector("#canvas").style.height=
e+"px"):s_oStage&&(s_oStage.canvas.width=k,s_oStage.canvas.height=e,s_iScaleFactor=Math.min(k/CANVAS_WIDTH,e/CANVAS_HEIGHT),s_oStage.scaleX=s_oStage.scaleY=s_iScaleFactor);0<=h&&(h=(a-e)/2);document.querySelector("#canvas").style.top=h+"px";document.querySelector("#canvas").style.left=d+"px";fullscreenHandler()}}
function _checkOrientation(a,g){s_bMobile&&ENABLE_CHECK_ORIENTATION&&(a>g?"landscape"===document.querySelector(".orientation-msg-container").getAttribute("data-orientation")?(document.querySelector(".orientation-msg-container").style.display="none",s_oMain.startUpdate()):(document.querySelector(".orientation-msg-container").style.display="block",s_oMain.stopUpdate()):"portrait"===document.querySelector(".orientation-msg-container").getAttribute("data-orientation")?(document.querySelector(".orientation-msg-container").style.display=
"none",s_oMain.startUpdate()):(document.querySelector(".orientation-msg-container").style.display="block",s_oMain.stopUpdate()))}function createBitmap(a,g,e){var k=new createjs.Bitmap(a),h=new createjs.Shape;g&&e?h.graphics.beginFill("#fff").drawRect(0,0,g,e):h.graphics.beginFill("#ff0").drawRect(0,0,a.width,a.height);k.hitArea=h;return k}
function createSprite(a,g,e,k,h,d){a=null!==g?new createjs.Sprite(a,g):new createjs.Sprite(a);g=new createjs.Shape;g.graphics.beginFill("#000000").drawRect(-e,-k,h,d);a.hitArea=g;return a}function randomFloatBetween(a,g,e){"undefined"===typeof e&&(e=2);return parseFloat(Math.min(a+Math.random()*(g-a),g).toFixed(e))}function shuffle(a){for(var g=a.length,e,k;0!==g;)k=Math.floor(Math.random()*g),--g,e=a[g],a[g]=a[k],a[k]=e;return a}
function formatTime(a){a/=1E3;var g=Math.floor(a/60);a=parseFloat(a-60*g).toFixed(1);var e="";e=10>g?e+("0"+g+":"):e+(g+":");return 10>a?e+("0"+a):e+a}function NoClickDelay(a){this.element=a;window.Touch&&this.element.addEventListener("touchstart",this,!1)}function shuffle(a){for(var g=a.length,e,k;0<g;)k=Math.floor(Math.random()*g),g--,e=a[g],a[g]=a[k],a[k]=e;return a}
NoClickDelay.prototype={handleEvent:function(a){switch(a.type){case "touchstart":this.onTouchStart(a);break;case "touchmove":this.onTouchMove(a);break;case "touchend":this.onTouchEnd(a)}},onTouchStart:function(a){a.preventDefault();this.moved=!1;this.element.addEventListener("touchmove",this,!1);this.element.addEventListener("touchend",this,!1)},onTouchMove:function(a){this.moved=!0},onTouchEnd:function(a){this.element.removeEventListener("touchmove",this,!1);this.element.removeEventListener("touchend",
this,!1);if(!this.moved){a=document.elementFromPoint(a.changedTouches[0].clientX,a.changedTouches[0].clientY);3==a.nodeType&&(a=a.parentNode);var g=document.createEvent("MouseEvents");g.initEvent("click",!0,!0);a.dispatchEvent(g)}}};
(function(){function a(e){var k={focus:"visible",focusin:"visible",pageshow:"visible",blur:"hidden",focusout:"hidden",pagehide:"hidden"};e=e||window.event;e.type in k?document.body.className=k[e.type]:(document.body.className=this[g]?"hidden":"visible","hidden"===document.body.className?(s_oMain.stopUpdate(),s_bFocus=!1):(s_oMain.startUpdate(),s_bFocus=!0))}var g="hidden";g in document?document.addEventListener("visibilitychange",a):(g="mozHidden")in document?document.addEventListener("mozvisibilitychange",
a):(g="webkitHidden")in document?document.addEventListener("webkitvisibilitychange",a):(g="msHidden")in document?document.addEventListener("msvisibilitychange",a):"onfocusin"in document?document.onfocusin=document.onfocusout=a:window.onpageshow=window.onpagehide=window.onfocus=window.onblur=a})();function ctlArcadeResume(){null!==s_oMain&&s_oMain.startUpdate()}function ctlArcadePause(){null!==s_oMain&&s_oMain.stopUpdate()}
function getParamValue(a){for(var g=window.location.search.substring(1).split("&"),e=0;e<g.length;e++){var k=g[e].split("=");if(k[0]==a)return k[1]}}function playSound(a,g,e){return!1===DISABLE_SOUND_MOBILE||!1===s_bMobile?(s_aSounds[a].play(),s_aSounds[a].volume(g),s_aSounds[a].loop(e),s_aSounds[a]):null}function stopSound(a){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||s_aSounds[a].stop()}function setVolume(a,g){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||s_aSounds[a].volume(g)}
function setMute(a,g){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||s_aSounds[a].mute(g)}function isSoundPlaying(a){return s_aSounds[a].playing()}function saveItem(a,g){s_bStorageAvailable&&localStorage.setItem(a,g)}function getItem(a){return s_bStorageAvailable?localStorage.getItem(a):null}
function fullscreenHandler(){ENABLE_FULLSCREEN&&!1!==screenfull.isEnabled&&(s_bFullscreen=screenfull.isFullscreen,null!==s_oInterface&&s_oInterface.resetFullscreenBut(),null!==s_oMenu&&s_oMenu.resetFullscreenBut(),null!==s_oLevelMenu&&s_oLevelMenu.resetFullscreenBut())}if(screenfull.isEnabled)screenfull.on("change",function(){s_bFullscreen=screenfull.isFullscreen;null!==s_oInterface&&s_oInterface.resetFullscreenBut();null!==s_oMenu&&s_oMenu.resetFullscreenBut();null!==s_oLevelMenu&&s_oLevelMenu.resetFullscreenBut()});
function CSpriteLibrary(){var a={},g,e,k,h,d,f;this.init=function(b,n,c){g={};k=e=0;h=b;d=n;f=c};this.addSprite=function(b,n){if(!a.hasOwnProperty(b)){var c=new Image;a[b]=g[b]={szPath:n,oSprite:c,bLoaded:!1};e++}};this.getSprite=function(b){return a.hasOwnProperty(b)?a[b].oSprite:null};this._onSpritesLoaded=function(){e=0;d.call(f)};this._onSpriteLoaded=function(){h.call(f);++k===e&&this._onSpritesLoaded()};this.loadSprites=function(){for(var b in g)g[b].oSprite.oSpriteLibrary=this,g[b].oSprite.szKey=
b,g[b].oSprite.onload=function(){this.oSpriteLibrary.setLoaded(this.szKey);this.oSpriteLibrary._onSpriteLoaded(this.szKey)},g[b].oSprite.onerror=function(n){var c=n.currentTarget;setTimeout(function(){g[c.szKey].oSprite.src=g[c.szKey].szPath},500)},g[b].oSprite.src=g[b].szPath};this.setLoaded=function(b){a[b].bLoaded=!0};this.isLoaded=function(b){return a[b].bLoaded};this.getNumSprites=function(){return e}}
var CANVAS_WIDTH=1500,CANVAS_HEIGHT=768,EDGEBOARD_X=180,EDGEBOARD_Y=20,FPS=30,FPS_TIME=1E3/FPS,DISABLE_SOUND_MOBILE=!1,FONT_GAME="space_marine",STATE_LOADING=0,STATE_MENU=1,STATE_MENU_LEVEL=2,STATE_GAME=3,ON_MOUSE_DOWN=0,ON_MOUSE_UP=1,ON_MOUSE_OVER=2,ON_MOUSE_OUT=3,ON_DRAG_START=4,ON_DRAG_END=5,ON_BUT_YES_DOWN=6,ON_PLAYER_TOUCHDOWN=7,ON_PLAYER_TACKLED=8,ON_OPPONENT_HIDE=9,ON_OPPONENT_TACKLE=10,ON_POWERUP_END_MOVE=11,ON_BACK_MENU=12,ON_RESTART=13,ON_NEXT_LEVEL=14,PLAYER_ANIM_RUN=0,PLAYER_ANIM_FALL=
1,PLAYER_ANIM_TOUCHDOWN=2,PLAYER_ANIM_JUMP=3,STARTING_STANDS_SCALE_BONUS=.74,NUM_LEVELS,OPPONENT_FINAL_Y=1070,POWERUP_FINAL_Y=600,TIME_OPPONENT_RUN=3E3,HERO_ACCELERATION,HERO_SUPER_ACCELERATION,HERO_FRICTION,MAX_HERO_SPEED,MAX_DIST_AVOID_OPPONENT_IN_JUMP=150,MIN_POWERUP_X=700,MAX_POWERUP_X=800,SCORE_POWERUP,TIME_EFFECT_POWERUP=1E4,NUM_COLS_PAGE_LEVEL=6,NUM_ROWS_PAGE_LEVEL=2,SOUNDTRACK_VOLUME_IN_GAME=1,ENABLE_FULLSCREEN,ENABLE_CHECK_ORIENTATION;
function CPreloader(){var a,g,e,k,h,d,f,b,n;this._init=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("progress_bar","./sprites/progress_bar.png");s_oSpriteLibrary.addSprite("200x200","./sprites/200x200.jpg");s_oSpriteLibrary.loadSprites();n=new createjs.Container;s_oStage.addChild(n)};this.unload=function(){n.removeAllChildren()};this._onImagesLoaded=function(){};this._onAllImagesLoaded=function(){this.attachSprites();s_oMain.preloaderReady()};
this.attachSprites=function(){var c=new createjs.Shape;c.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);n.addChild(c);c=s_oSpriteLibrary.getSprite("200x200");f=createBitmap(c);f.regX=.5*c.width;f.regY=.5*c.height;f.x=CANVAS_WIDTH/2;f.y=CANVAS_HEIGHT/2-80;n.addChild(f);b=new createjs.Shape;b.graphics.beginFill("rgba(0,0,0,0.01)").drawRoundRect(f.x-100,f.y-100,200,200,10);n.addChild(b);f.mask=b;c=s_oSpriteLibrary.getSprite("progress_bar");k=createBitmap(c);k.x=CANVAS_WIDTH/2-c.width/
2;k.y=CANVAS_HEIGHT/2+70;n.addChild(k);a=c.width;g=c.height;h=new createjs.Shape;h.graphics.beginFill("rgba(0,0,0,0.01)").drawRect(k.x,k.y,1,g);n.addChild(h);k.mask=h;e=new createjs.Text("","30px "+FONT_GAME,"#fff");e.x=CANVAS_WIDTH/2;e.y=CANVAS_HEIGHT/2+120;e.textBaseline="alphabetic";e.textAlign="center";n.addChild(e);d=new createjs.Shape;d.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);n.addChild(d);createjs.Tween.get(d).to({alpha:0},500).call(function(){createjs.Tween.removeTweens(d);
n.removeChild(d)})};this.refreshLoader=function(c){e.text=c+"%";100===c&&(s_oMain._allResourcesLoaded(),e.visible=!1,k.visible=!1);h.graphics.clear();c=Math.floor(c*a/100);h.graphics.beginFill("rgba(0,0,0,0.01)").drawRect(k.x,k.y,c,g)};this._init()}
function CMain(a){var g,e,k=0,h=0,d=STATE_LOADING,f,b,n;this.initContainer=function(){var c=document.getElementById("canvas");s_oStage=new createjs.Stage(c);s_oStage.preventSelection=!1;s_bMobile=isMobile();!1===s_bMobile?s_oStage.enableMouseOver(20):createjs.Touch.enable(s_oStage);s_iPrevTime=(new Date).getTime();createjs.Ticker.framerate=FPS;createjs.Ticker.on("tick",this._update);navigator.userAgent.match(/Windows Phone/i)&&(DISABLE_SOUND_MOBILE=!0);s_oSpriteLibrary=new CSpriteLibrary;s_oLevelSettings=
new CLevelSettings;f=new CPreloader};this.setLocalStorageLevel=function(c){var t=getItem("touchdownrush_level");if(null===t||t<c)s_iLastLevel=c,saveItem("touchdownrush_level",s_iLastLevel)};this.setLocalStorageScore=function(c,t){saveItem("touchdownrush_score_level_"+t,c)};this.clearLocalStorage=function(){s_iLastLevel=1;s_bStorageAvailable&&localStorage.clear()};this.getScoreTillLevel=function(c){if(!s_bStorageAvailable)return 0;for(var t=0,u=0;u<c-1;u++)t+=parseInt(getItem("touchdownrush_score_level_"+
(u+1)));return t};this.getSavedLevel=function(){if(!s_bStorageAvailable)return 1;var c=getItem("touchdownrush_level");return null===c?1:c};this.preloaderReady=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||this._initSounds();this._loadImages();g=e=!0};this.soundLoaded=function(){k++;f.refreshLoader(Math.floor(k/h*100))};this._initSounds=function(){Howler.mute(!s_bAudioActive);s_aSoundsInfo=[];s_aSoundsInfo.push({path:"./sounds/",filename:"click",loop:!1,volume:1,ingamename:"click"});s_aSoundsInfo.push({path:"./sounds/",
filename:"level_win",loop:!1,volume:1,ingamename:"level_win"});s_aSoundsInfo.push({path:"./sounds/",filename:"powerup",loop:!1,volume:1,ingamename:"powerup"});s_aSoundsInfo.push({path:"./sounds/",filename:"crowd_touchdown",loop:!1,volume:1,ingamename:"crowd_touchdown"});s_aSoundsInfo.push({path:"./sounds/",filename:"enemy",loop:!1,volume:1,ingamename:"enemy"});s_aSoundsInfo.push({path:"./sounds/",filename:"enemy_tackle",loop:!1,volume:1,ingamename:"enemy_tackle"});s_aSoundsInfo.push({path:"./sounds/",
filename:"game_over",loop:!1,volume:1,ingamename:"game_over"});s_aSoundsInfo.push({path:"./sounds/",filename:"crowd_idle",loop:!0,volume:1,ingamename:"crowd_idle"});s_aSoundsInfo.push({path:"./sounds/",filename:"soundtrack",loop:!0,volume:1,ingamename:"soundtrack"});h+=s_aSoundsInfo.length;s_aSounds=[];for(var c=0;c<s_aSoundsInfo.length;c++)this.tryToLoadSound(s_aSoundsInfo[c],!1)};this.tryToLoadSound=function(c,t){setTimeout(function(){s_aSounds[c.ingamename]=new Howl({src:[c.path+c.filename+".mp3"],
autoplay:!1,preload:!0,loop:c.loop,volume:c.volume,onload:s_oMain.soundLoaded,onloaderror:function(u,m){for(var r=0;r<s_aSoundsInfo.length;r++)if(u===s_aSounds[s_aSoundsInfo[r].ingamename]._sounds[0]._id){s_oMain.tryToLoadSound(s_aSoundsInfo[r],!0);break}},onplayerror:function(u){for(var m=0;m<s_aSoundsInfo.length;m++)if(u===s_aSounds[s_aSoundsInfo[m].ingamename]._sounds[0]._id){s_aSounds[s_aSoundsInfo[m].ingamename].once("unlock",function(){s_aSounds[s_aSoundsInfo[m].ingamename].play();"soundtrack"===
s_aSoundsInfo[m].ingamename&&null!==s_oGame&&setVolume("soundtrack",SOUNDTRACK_VOLUME_IN_GAME)});break}}})},t?200:0)};this._loadImages=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("but_play","./sprites/but_play.png");s_oSpriteLibrary.addSprite("but_next","./sprites/but_next.png");s_oSpriteLibrary.addSprite("but_exit","./sprites/but_exit.png");s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("audio_icon",
"./sprites/audio_icon.png");s_oSpriteLibrary.addSprite("msg_box","./sprites/msg_box.png");s_oSpriteLibrary.addSprite("msg_box_big","./sprites/msg_box_big.png");s_oSpriteLibrary.addSprite("msg_box_wide","./sprites/msg_box_wide.png");s_oSpriteLibrary.addSprite("bg_game","./sprites/bg_game.jpg");s_oSpriteLibrary.addSprite("bg_menu_level","./sprites/bg_menu_level.jpg");s_oSpriteLibrary.addSprite("logo_ctl","./sprites/logo_ctl.png");s_oSpriteLibrary.addSprite("but_credits","./sprites/but_credits.png");
s_oSpriteLibrary.addSprite("but_yes","./sprites/but_yes.png");s_oSpriteLibrary.addSprite("but_no","./sprites/but_no.png");s_oSpriteLibrary.addSprite("but_fullscreen","./sprites/but_fullscreen.png");s_oSpriteLibrary.addSprite("but_settings","./sprites/but_settings.png");s_oSpriteLibrary.addSprite("but_home","./sprites/but_home.png");s_oSpriteLibrary.addSprite("but_restart","./sprites/but_restart.png");s_oSpriteLibrary.addSprite("key_0","./sprites/key_0.png");s_oSpriteLibrary.addSprite("key_1","./sprites/key_1.png");
s_oSpriteLibrary.addSprite("key_2","./sprites/key_2.png");s_oSpriteLibrary.addSprite("but_left","./sprites/but_left.png");s_oSpriteLibrary.addSprite("but_right","./sprites/but_right.png");s_oSpriteLibrary.addSprite("but_jump","./sprites/but_jump.png");s_oSpriteLibrary.addSprite("post","./sprites/post.png");s_oSpriteLibrary.addSprite("power_up_0","./sprites/power_up_0.png");s_oSpriteLibrary.addSprite("power_up_1","./sprites/power_up_1.png");s_oSpriteLibrary.addSprite("but_level","./sprites/but_level.png");
s_oSpriteLibrary.addSprite("powerup_gui_off","./sprites/powerup_gui_off.png");s_oSpriteLibrary.addSprite("powerup_gui_on","./sprites/powerup_gui_on.png");s_oSpriteLibrary.addSprite("player_falling","./sprites/player/player_falling.png");s_oSpriteLibrary.addSprite("player_jump-0","./sprites/player/player_jump-0.png");s_oSpriteLibrary.addSprite("player_jump-1","./sprites/player/player_jump-1.png");s_oSpriteLibrary.addSprite("player_jump-2","./sprites/player/player_jump-2.png");s_oSpriteLibrary.addSprite("player_running-0",
"./sprites/player/player_running-0.png");s_oSpriteLibrary.addSprite("player_running-1","./sprites/player/player_running-1.png");s_oSpriteLibrary.addSprite("player_touchdown-0","./sprites/player/player_touchdown-0.png");s_oSpriteLibrary.addSprite("player_touchdown-1","./sprites/player/player_touchdown-1.png");for(var c=0;18>c;c++)s_oSpriteLibrary.addSprite("field_loop_"+c,"./sprites/field_loop/field_loop_"+c+".png");for(c=0;39>c;c++)s_oSpriteLibrary.addSprite("end_zone_"+c,"./sprites/end_zone/end_zone_"+
c+".png");for(c=0;18>c;c++)s_oSpriteLibrary.addSprite("enemy_running_"+c,"./sprites/enemy/running/enemy_running_"+c+".png");for(c=0;18>c;c++)s_oSpriteLibrary.addSprite("enemy_tackle_"+c,"./sprites/enemy/tackle/enemy_tackle_"+c+".png");h+=s_oSpriteLibrary.getNumSprites();s_oSpriteLibrary.loadSprites()};this._onImagesLoaded=function(){k++;f.refreshLoader(Math.floor(k/h*100))};this._onAllImagesLoaded=function(){};this._allResourcesLoaded=function(){f.unload();try{saveItem("ls_available","ok"),s_iLastLevel=
this.getSavedLevel()}catch(c){s_bStorageAvailable=!1}playSound("soundtrack",1,!0);s_oMain.gotoMenu()};this.gotoMenu=function(){new CMenu;d=STATE_MENU};this.gotoLevelMenu=function(){b=new CLevelMenu;d=STATE_MENU_LEVEL};this.gotoSelectCar=function(){new CMenuSelectCar;d=STATE_MENU_SELECT_CAR};this.gotoGame=function(){n=new CGame;d=STATE_GAME};this.levelSelected=function(c){s_iLevelSelected=c;b.unload();c>=s_iLastLevel&&(s_iLastLevel=c);s_oMain.gotoGame()};this.stopUpdateNoBlockAndTick=function(){e=
!1};this.startUpdateNoBlockAndTick=function(){e=!0};this.stopUpdateNoBlock=function(){g=!1;createjs.Ticker.paused=!0};this.startUpdateNoBlock=function(){s_iPrevTime=(new Date).getTime();g=!0;createjs.Ticker.paused=!1};this.stopUpdate=function(){g=!1;createjs.Ticker.paused=!0;document.querySelector("#block_game").style.display="block";!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||Howler.mute(!0)};this.startUpdate=function(){s_iPrevTime=(new Date).getTime();g=!0;createjs.Ticker.paused=!1;document.querySelector("#block_game").style.display=
"none";(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)&&s_bAudioActive&&Howler.mute(!1)};this._update=function(c){if(!1!==g){var t=(new Date).getTime();s_iTimeElaps=t-s_iPrevTime;s_iCntTime+=s_iTimeElaps;s_iCntFps++;s_iPrevTime=t;1E3<=s_iCntTime&&(s_iCurFps=s_iCntFps,s_iCntTime-=1E3,s_iCntFps=0);d===STATE_GAME&&e&&n.update();void 0!==s_oStage&&s_oStage.update(c)}};s_oMain=this;HERO_ACCELERATION=a.hero_acceleration;HERO_SUPER_ACCELERATION=a.hero_acceleration_powerup;HERO_FRICTION=a.hero_friction;MAX_HERO_SPEED=
a.max_hero_speed;SCORE_POWERUP=a.score_powerup;ENABLE_FULLSCREEN=a.fullscreen;ENABLE_CHECK_ORIENTATION=a.check_orientation;this.initContainer()}var s_bMobile,s_bAudioActive=!1,s_iCntTime=0,s_iTimeElaps=0,s_iPrevTime=0,s_iCntFps=0,s_iCurFps=0,s_oDrawLayer,s_oStage,s_oMain=null,s_oSpriteLibrary,s_oLevelSettings,s_iLastLevel,s_iLevelSelected=1,s_bFullscreen=!1,s_bStorageAvailable=!0,s_aSoundsInfo;
function CTextButton(a,g,e,k,h,d,f,b){var n,c,t,u,m,r,q,y,D;this._init=function(A,p,F,z,w,v,H,x){n=!1;u=[];m=[];D=createBitmap(F);c=F.width;t=F.height;y=new createjs.Text(z,H+"px "+w,v);y.textAlign="center";y.textBaseline="alphabetic";y.lineWidth=.9*c;y.x=F.width/2;y.y=Math.floor(F.height/2)+15;q=new createjs.Container;q.x=A;q.y=p;q.regX=F.width/2;q.regY=F.height/2;s_bMobile||(q.cursor="pointer");q.addChild(D,y);!1!==x&&s_oStage.addChild(q);this._initListener()};this.unload=function(){q.off("mousedown");
q.off("pressup");s_oStage.removeChild(q)};this.setVisible=function(A){q.visible=A};this.setAlign=function(A){y.textAlign=A};this.enable=function(){n=!1;D.filters=[];D.cache(0,0,c,t)};this.disable=function(){n=!0;var A=(new createjs.ColorMatrix).adjustSaturation(-100).adjustBrightness(40);D.filters=[new createjs.ColorMatrixFilter(A)];D.cache(0,0,c,t)};this._initListener=function(){q.on("mousedown",this.buttonDown);q.on("pressup",this.buttonRelease)};this.addEventListener=function(A,p,F){u[A]=p;m[A]=
F};this.addEventListenerWithParams=function(A,p,F,z){u[A]=p;m[A]=F;r=z};this.buttonRelease=function(){n||(playSound("click",1,!1),q.scaleX=1,q.scaleY=1,u[ON_MOUSE_UP]&&u[ON_MOUSE_UP].call(m[ON_MOUSE_UP],r))};this.buttonDown=function(){n||(q.scaleX=.9,q.scaleY=.9,u[ON_MOUSE_DOWN]&&u[ON_MOUSE_DOWN].call(m[ON_MOUSE_DOWN]))};this.setPosition=function(A,p){q.x=A;q.y=p};this.changeText=function(A){y.text=A};this.setX=function(A){q.x=A};this.setY=function(A){q.y=A};this.getButtonImage=function(){return q};
this.getX=function(){return q.x};this.getY=function(){return q.y};this.getSprite=function(){return q};this._init(a,g,e,k,h,d,f,b);return this}
function CGfxButton(a,g,e,k){var h,d,f,b=[],n,c,t;this._init=function(u,m,r){h=!1;d=[];f=[];t=createBitmap(r);t.x=u;t.y=m;t.regX=r.width/2;t.regY=r.height/2;t.cursor="pointer";k.addChild(t);this._initListener()};this.unload=function(){t.off("mousedown",n);t.off("pressup",c);k.removeChild(t)};this.setVisible=function(u){t.visible=u};this._initListener=function(){n=t.on("mousedown",this.buttonDown);c=t.on("pressup",this.buttonRelease)};this.addEventListener=function(u,m,r){d[u]=m;f[u]=r};this.addEventListenerWithParams=
function(u,m,r,q){d[u]=m;f[u]=r;b=q};this.enable=function(){h=!1};this.disable=function(){h=!0};this.buttonRelease=function(){h||(playSound("click",1,!1),t.scaleX=1,t.scaleY=1,d[ON_MOUSE_UP]&&d[ON_MOUSE_UP].call(f[ON_MOUSE_UP],b))};this.buttonDown=function(){h||(t.scaleX=.9,t.scaleY=.9,d[ON_MOUSE_DOWN]&&d[ON_MOUSE_DOWN].call(f[ON_MOUSE_DOWN],b))};this.setPosition=function(u,m){t.x=u;t.y=m};this.setX=function(u){t.x=u};this.setY=function(u){t.y=u};this.getButtonImage=function(){return t};this.getX=
function(){return t.x};this.getY=function(){return t.y};this._init(a,g,e);return this}
function CToggle(a,g,e,k,h){var d,f,b,n;this._init=function(c,t,u,m){f=[];b=[];var r=new createjs.SpriteSheet({images:[u],frames:{width:u.width/2,height:u.height,regX:u.width/2/2,regY:u.height/2},animations:{state_true:[0],state_false:[1]}});d=m;n=createSprite(r,"state_"+d,u.width/2/2,u.height/2,u.width/2,u.height);n.x=c;n.y=t;n.stop();n.cursor="pointer";h.addChild(n);this._initListener()};this.unload=function(){n.off("mousedown",this.buttonDown);n.off("pressup",this.buttonRelease);h.removeChild(n)};
this._initListener=function(){n.on("mousedown",this.buttonDown);n.on("pressup",this.buttonRelease)};this.addEventListener=function(c,t,u){f[c]=t;b[c]=u};this.setActive=function(c){d=c;n.gotoAndStop("state_"+d)};this.buttonRelease=function(){n.scaleX=1;n.scaleY=1;playSound("click",1,!1);d=!d;n.gotoAndStop("state_"+d);f[ON_MOUSE_UP]&&f[ON_MOUSE_UP].call(b[ON_MOUSE_UP],d)};this.buttonDown=function(){n.scaleX=.9;n.scaleY=.9;f[ON_MOUSE_DOWN]&&f[ON_MOUSE_DOWN].call(b[ON_MOUSE_DOWN])};this.setPosition=function(c,
t){n.x=c;n.y=t};this.getButtonImage=function(){return n};this._init(a,g,e,k)}
function CMenu(){var a,g,e,k,h,d,f,b,n,c,t,u,m=null,r=null;this._init=function(){f=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));s_oStage.addChild(f);b=new CGfxButton(CANVAS_WIDTH/2+150,CANVAS_HEIGHT-150,s_oSpriteLibrary.getSprite("but_play"),s_oStage);b.addEventListener(ON_MOUSE_UP,this._onButPlaySingle,this);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile){var q=s_oSpriteLibrary.getSprite("audio_icon");h=CANVAS_WIDTH-q.height/2-10;d=q.height/2+10;n=new CToggle(h,d,q,s_bAudioActive,s_oStage);
n.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this)}q=s_oSpriteLibrary.getSprite("but_credits");e=q.width/2+10;k=q.height/2+10;c=new CGfxButton(e,k,q,s_oStage);c.addEventListener(ON_MOUSE_UP,this._onButCreditsRelease,this);q=window.document;var y=q.documentElement;m=y.requestFullscreen||y.mozRequestFullScreen||y.webkitRequestFullScreen||y.msRequestFullscreen;r=q.exitFullscreen||q.mozCancelFullScreen||q.webkitExitFullscreen||q.msExitFullscreen;!1===ENABLE_FULLSCREEN&&(m=!1);m&&screenfull.isEnabled&&
(q=s_oSpriteLibrary.getSprite("but_fullscreen"),a=e+q.width/2+10,g=k,u=new CToggle(a,g,q,s_bFullscreen,s_oStage),u.addEventListener(ON_MOUSE_UP,this._onFullscreenRelease,this));s_bStorageAvailable||new CAlertSavingBox(TEXT_ERR_LS,s_oStage);t=new createjs.Shape;t.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(t);createjs.Tween.get(t).to({alpha:0},400).call(function(){t.visible=!1});setVolume("soundtrack",1);this.refreshButtonPos()};this.unload=function(){b.unload();
c.unload();if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)n.unload(),n=null;m&&screenfull.isEnabled&&u.unload();s_oStage.removeAllChildren();s_oMenu=null};this.refreshButtonPos=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||n.setPosition(h-s_iOffsetX,s_iOffsetY+d);m&&screenfull.isEnabled&&u.setPosition(a+s_iOffsetX,g+s_iOffsetY);c.setPosition(e+s_iOffsetX,k+s_iOffsetY)};this._onButPlaySingle=function(){s_oMenu.unload();s_oMain.gotoLevelMenu();document.dispatchEvent(new CustomEvent("start_session"))};
this._onButCreditsRelease=function(){new CCreditsPanel};this._onAudioToggle=function(){Howler.mute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this.resetFullscreenBut=function(){m&&screenfull.isEnabled&&u.setActive(s_bFullscreen)};this._onFullscreenRelease=function(){s_bFullscreen?r.call(window.document):m.call(window.document.documentElement);sizeHandler()};s_oMenu=this;this._init()}var s_oMenu=null;
function CGame(){var a=!1,g,e,k,h,d,f,b,n,c,t,u,m,r,q,y,D,A,p,F,z,w,v,H,x,P,O,Q,I,T,R,W;this._init=function(){b=s_iLevelSelected;d=s_oMain.getScoreTillLevel(b);z=[{x:10,y:0},{x:-20,y:0},{x:10,y:-10},{x:0,y:20},{x:10,y:-10},{x:-10,y:0},{x:10,y:0},{x:-20,y:0},{x:10,y:-10},{x:0,y:20},{x:10,y:-10},{x:-10,y:0}];O=new createjs.Container;s_oStage.addChild(O);var B=s_oSpriteLibrary.getSprite("bg_game");w=createBitmap(B);w.regX=B.width/2;w.regY=B.height;w.x=CANVAS_WIDTH/2;w.y=521;O.addChild(w);H=new CField(0,
516,O);H.show();x=new CFieldEndZone(0,516,O);B=s_oSpriteLibrary.getSprite("post");v=createBitmap(B);v.regX=B.width/2;v.regY=B.height;v.x=CANVAS_WIDTH-450;v.y=518;O.addChild(v);Q=new createjs.Container;O.addChild(Q);I=new CPlayer(CANVAS_WIDTH/2,CANVAS_HEIGHT-s_iOffsetY,O);I.addEventListener(ON_PLAYER_TOUCHDOWN,this._onWinLevel,this);I.addEventListener(ON_PLAYER_TACKLED,this._onEndLevel,this);P=new CInterface(d);this.reset();T=new CHelpPanel;T.show();R=new CEndPanel;R.addEventListener(ON_RESTART,this.restart,
this);R.addEventListener(ON_BACK_MENU,this.onExit,this);W=new CNextLevelPanel;W.addEventListener(ON_RESTART,this.restart,this);W.addEventListener(ON_BACK_MENU,this.onExit,this);W.addEventListener(ON_NEXT_LEVEL,this._onNextLevel,this);playSound("crowd_idle",1,!0)};this.unload=function(){a=!1;stopSound("crowd_idle");P.unload();s_oStage.removeAllChildren()};this.reset=function(){g=h=e=k=!1;n=f=0;D=[];A=[];c=s_oLevelSettings.getEnemiesSpawn(b);t=s_oLevelSettings.getStartingEnemySpawn(b);u=s_oLevelSettings.getEnemySpawnNumber(b);
F=s_oLevelSettings.getPowerUps(b);d=s_oMain.getScoreTillLevel(b);m=parseFloat(((1-STARTING_STANDS_SCALE_BONUS)/c).toFixed(3));this._createSpawnArray();x.reset();I.reset();P.reset(d,b);w.scaleX=w.scaleY=STARTING_STANDS_SCALE_BONUS;v.scaleX=v.scaleY=.2;setVolume("crowd_idle",1);document.dispatchEvent(new CustomEvent("start_level",{detail:{level:b}}))};this.restart=function(){document.dispatchEvent(new CustomEvent("restart_level",{detail:{level:b}}));for(var B=0;B<A.length;B++)A[B].unload();this.reset();
this.startCountdown()};this.refreshButtonPos=function(){P.refreshButtonPos();I.setY(CANVAS_HEIGHT-s_iOffsetY)};this.onKeyDown=function(B){if(I.isJumping()||h||I.getCurAnim()===PLAYER_ANIM_TOUCHDOWN)return B.preventDefault(),!1;B||(B=window.event);switch(B.keyCode){case 37:e=!0;I.moveLeft(!0);break;case 39:e=!0;I.moveRight(!0);break;case 32:e=!0,I.jump()}B.preventDefault();return!1};this.onKeyUp=function(B){if(h)return B.preventDefault(),!1;B||(B=window.event);e=!1;switch(B.keyCode){case 37:I.moveLeft(!1);
break;case 39:I.moveRight(!1)}B.preventDefault();return!1};this.moveLeft=function(B){B&&(e||I.isJumping())||h||(e=B,I.moveLeft(B))};this.moveRight=function(B){B&&(e||I.isJumping())||h||(e=B,I.moveRight(B))};this.moveJump=function(B){B&&(e||I.isJumping())||h||(e=B)&&I.jump()};this.startCountdown=function(){I.show();this._spawnEnemy();a=!0};this._createSpawnArray=function(){p=[];var B=s_iOffsetX+50,G=Math.floor(Math.random()*(CANVAS_WIDTH-s_iOffsetX-s_iOffsetX+1))+s_iOffsetX+50;for(G/=s_oLevelSettings.getEnemiesSpawn(b);B<
CANVAS_WIDTH-s_iOffsetX;)p.push(B),B+=G;p=shuffle(p)};this.onExitFromHelp=function(){this.startCountdown()};this._spawnEnemy=function(){for(var B=Math.floor(Math.random()*u)+1,G=0;G<B&&0!==c;G++){c--;var M=!1;0===c&&(k=M=!0);M=new COpponent(M,p.pop(),526,Q);M.addEventListener(ON_OPPONENT_HIDE,this.checkTouchDown,this);M.addEventListener(ON_OPPONENT_TACKLE,this.checkCollision,this);D.push(M);M=w.scaleX+m;(new createjs.Tween.get(w)).to({scaleX:M,scaleY:M},t);M=v.scaleX+m;(new createjs.Tween.get(v)).to({scaleX:M,
scaleY:M,x:v.x+750*m},t);-1!==F.indexOf(D.length)&&this._spawnPowerUp()}};this._spawnPowerUp=function(){var B=new CPowerUp(Math.floor(Math.random()*(MAX_POWERUP_X-MIN_POWERUP_X+1))+MIN_POWERUP_X,510,Math.floor(2*Math.random()),Q);B.addEventListener(ON_POWERUP_END_MOVE,this._checkCollisionWithPowerUp,this);A.push(B)};this.checkTouchDown=function(B){B&&!h&&this._showTouchdown()};this.checkCollision=function(B){if(!h){var G=I.getRect(),M=Math.abs(B.x-G.x);if(G.intersects(B))if(I.isJumping()&&M>MAX_DIST_AVOID_OPPONENT_IN_JUMP)this.refreshScore(Math.floor(M/
200));else{h=!0;r=0;var l=this;q=setInterval(function(){l.tremble()},20);playSound("enemy_tackle",1,!1);I.changeAnim(PLAYER_ANIM_FALL);for(B=0;B<A.length;B++)A[B].stopTween()}else this.refreshScore(Math.floor(M/200))}};this._checkCollisionWithPowerUp=function(B,G){if(!h&&I.getRect().intersects(B))switch(playSound("powerup",1,!1),G){case 0:this.refreshScore(SCORE_POWERUP);new CScoreText(SCORE_POWERUP,CANVAS_WIDTH/2,CANVAS_HEIGHT/2,s_oStage);break;case 1:I.setAcceleration(HERO_SUPER_ACCELERATION,2*
MAX_HERO_SPEED),y=0,g=!0,P.showPowerUpGui()}};this.tremble=function(){var B=z[r];O.x+=B.x;O.y+=B.y;r++;r===z.length&&(r=0,clearInterval(q))};this.refreshScore=function(B){f+=B;d+=B;P.refreshScore(d)};this._showTouchdown=function(){playSound("crowd_touchdown",1,!1);x.show();var B=w.scaleX+m;(new createjs.Tween.get(w)).to({scaleX:B,scaleY:B},1200);B=v.scaleX+m;(new createjs.Tween.get(v)).to({scaleX:B,scaleY:B,x:v.x+500,y:v.y+60},1E3);setTimeout(function(){I.changeAnim(PLAYER_ANIM_TOUCHDOWN)},500)};
this._manageOpponentDepth=function(){Q.sortChildren(function(B,G,M){return B.y>G.y?1:B.y<G.y?-1:0})};this.endZonePlayed=function(){};this._onEndLevel=function(){document.dispatchEvent(new CustomEvent("end_level",{detail:{level:b}}));setVolume("crowd_idle",0);setTimeout(function(){R.show(d,TEXT_GAME_OVER)},2E3)};this._onWinLevel=function(){setVolume("crowd_idle",0);document.dispatchEvent(new CustomEvent("end_level",{detail:{level:b}}));document.dispatchEvent(new CustomEvent("save_score",{detail:{score:d}}));
b===NUM_LEVELS?setTimeout(function(){R.show(d,TEXT_CONGRATS)},2E3):(s_oMain.setLocalStorageLevel(b+1),s_oMain.setLocalStorageScore(f,b),setTimeout(function(){W.show(f,d,b)},2E3))};this._onNextLevel=function(){b++;this.reset();this.startCountdown()};this.onExit=function(){this.unload();s_oMain.gotoMenu();document.dispatchEvent(new CustomEvent("show_interlevel_ad"));document.dispatchEvent(new CustomEvent("end_session"));document.dispatchEvent(new CustomEvent("share_event",{detail:{score:d}}))};this.getPlayerX=
function(){return I.getX()};this.update=function(){if(!1!==a){I.update();this._manageOpponentDepth();for(var B=0;B<D.length;B++)D[B].update();h||(H.update(),x.update(),n+=s_iTimeElaps,!k&&n>t&&(n=0,this._spawnEnemy()),g&&(y+=s_iTimeElaps,y>TIME_EFFECT_POWERUP?(g=!1,P.hidePowerUpGui(),I.setAcceleration(HERO_ACCELERATION,MAX_HERO_SPEED)):P.refreshPowerUpTime(y)))}};s_oGame=this;this._init()}var s_oGame=null;
function CInterface(a){var g,e,k,h,d,f,b,n,c,t,u,m,r,q,y,D,A,p,F,z,w,v,H,x,P,O,Q,I=null,T=null,R,W;this._init=function(B){if(s_bMobile){var G=s_oSpriteLibrary.getSprite("but_left");b=G.width/2+150;n=CANVAS_HEIGHT-G.height/2-20;P=new CGfxButton(b,n,G,s_oStage);P.addEventListener(ON_MOUSE_DOWN,this._onLeftDown,this);P.addEventListener(ON_MOUSE_UP,this._onLeftUp,this);G=s_oSpriteLibrary.getSprite("but_right");d=CANVAS_WIDTH-G.width/2-150;f=CANVAS_HEIGHT-G.height/2-20;O=new CGfxButton(d,f,G,s_oStage);
O.addEventListener(ON_MOUSE_DOWN,this._onRightDown,this);O.addEventListener(ON_MOUSE_UP,this._onRightUp,this);G=s_oSpriteLibrary.getSprite("but_jump");k=CANVAS_WIDTH/2;h=CANVAS_HEIGHT-G.height/2-20;Q=new CGfxButton(k,h,G,s_oStage);Q.addEventListener(ON_MOUSE_DOWN,this._onJumpDown,this);Q.addEventListener(ON_MOUSE_UP,this._onJumpUp,this)}else document.onkeydown=s_oGame.onKeyDown,document.onkeyup=s_oGame.onKeyUp;G=s_oSpriteLibrary.getSprite("but_exit");g=CANVAS_WIDTH-G.width/2-10;e=G.height/2+10;w=
new CGfxButton(g,e,G,s_oStage);w.addEventListener(ON_MOUSE_UP,this._onExit,this);!1===DISABLE_SOUND_MOBILE||!1===s_bMobile?(y=g-G.width,D=e,G=s_oSpriteLibrary.getSprite("audio_icon"),H=new CToggle(y,D,G,s_bAudioActive,s_oStage),H.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this),c=y-G.width/2,t=D):(c=g-G.width,t=e);G=window.document;var M=G.documentElement;I=M.requestFullscreen||M.mozRequestFullScreen||M.webkitRequestFullScreen||M.msRequestFullscreen;T=G.exitFullscreen||G.mozCancelFullScreen||
G.webkitExitFullscreen||G.msExitFullscreen;!1===ENABLE_FULLSCREEN&&(I=!1);I&&screenfull.isEnabled&&(G=s_oSpriteLibrary.getSprite("but_fullscreen"),x=new CToggle(c,t,G,s_bFullscreen,s_oStage),x.addEventListener(ON_MOUSE_UP,this._onFullscreenRelease,this));G=s_oSpriteLibrary.getSprite("but_settings");R=new CGUIExpandible(g,e,G,s_oStage);R.addButton(w);!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||R.addButton(H);I&&screenfull.isEnabled&&R.addButton(x);r=10;q=40;F=new createjs.Text(TEXT_SCORE,"40px "+FONT_GAME,
"#fff");F.x=r;F.y=q;F.textBaseline="alphabetic";F.textAlign="left";F.shadow=new createjs.Shadow("#000000",2,2,5);s_oStage.addChild(F);p=new createjs.Text(B,"40px "+FONT_GAME,"#fff");p.x=F.x+20;p.y=q;p.textBaseline="alphabetic";p.textAlign="left";p.shadow=new createjs.Shadow("#000000",2,2,5);s_oStage.addChild(p);u=CANVAS_WIDTH/2;m=40;z=new createjs.Text(TEXT_LEVEL+" "+s_iLevelSelected,"40px "+FONT_GAME,"#fff");z.x=u;z.y=m;z.textBaseline="alphabetic";z.textAlign="center";z.shadow=new createjs.Shadow("#000000",
2,2,5);s_oStage.addChild(z);v=new CPowerUpGui(s_oStage);W=new CAreYouSurePanel;W.addEventListener(ON_BUT_YES_DOWN,this._onExitYes,this);A=new CRollingScore;this.refreshButtonPos()};this.unload=function(){w.unload();w=null;R.unload();W.unload();!1===DISABLE_SOUND_MOBILE&&(H.unload(),H=null);I&&screenfull.isEnabled&&x.unload();s_bMobile?(P.unload(),O.unload(),Q.unload()):(document.onkeydown=null,document.onkeyup=null);s_oStage.removeAllChildren();s_oInterface=null};this.reset=function(B,G){p.text=B;
z.text=TEXT_LEVEL+" "+G;v.reset()};this.refreshButtonPos=function(){F.x=r+s_iOffsetX;F.y=q+s_iOffsetY;p.x=F.x+F.getBounds().width+20;p.y=F.y;z.y=m+s_iOffsetY;R.refreshPos();s_bMobile&&(P.setPosition(b+s_iOffsetX,n-s_iOffsetY),O.setPosition(d-s_iOffsetX,f-s_iOffsetY),Q.setPosition(k,h-s_iOffsetY));v.refreshButtonPos()};this.refreshScore=function(B){A.rolling(p,null,B)};this.refreshPowerUpTime=function(B){v.refreshTime(B)};this.showPowerUpGui=function(){v.show()};this.hidePowerUpGui=function(){v.hide()};
this._onLeftDown=function(){s_oGame.moveLeft(!0)};this._onRightDown=function(){s_oGame.moveRight(!0)};this._onJumpDown=function(){s_oGame.moveJump(!0)};this._onLeftUp=function(){s_oGame.moveLeft(!1)};this._onRightUp=function(){s_oGame.moveRight(!1)};this._onJumpUp=function(){s_oGame.moveJump(!1)};this._onExit=function(){W.show(TEXT_ARE_SURE)};this._onAudioToggle=function(){Howler.mute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this.resetFullscreenBut=function(){I&&screenfull.isEnabled&&x.setActive(s_bFullscreen)};
this._onFullscreenRelease=function(){s_bFullscreen?T.call(window.document):I.call(window.document.documentElement);sizeHandler()};this._onExitYes=function(){s_oGame.onExit()};s_oInterface=this;this._init(a);return this}var s_oInterface=null;
function CHelpPanel(){var a,g,e,k,h,d,f,b,n,c,t,u=this;this._init=function(){t=new createjs.Container;t.visible=!1;s_oStage.addChild(t);k=new createjs.Shape;k.graphics.beginFill("rgba(0,0,0,0.7)").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);e=k.on("click",function(){});t.addChild(k);var m=s_oSpriteLibrary.getSprite("msg_box_wide"),r=createBitmap(m);r.regX=m.width/2;r.regY=m.height/2;r.x=CANVAS_WIDTH/2;r.y=CANVAS_HEIGHT/2;t.addChild(r);a=[];if(s_bMobile){r=s_oSpriteLibrary.getSprite("but_left");var q=
s_oSpriteLibrary.getSprite("but_right");m=s_oSpriteLibrary.getSprite("but_jump")}else r=s_oSpriteLibrary.getSprite("key_0"),q=s_oSpriteLibrary.getSprite("key_1"),m=s_oSpriteLibrary.getSprite("key_2");h=createBitmap(r);h.regX=r.width/2;h.regY=r.height/2;h.x=CANVAS_WIDTH/2-340;h.y=CANVAS_HEIGHT/2+130;t.addChild(h);a.push(h);d=createBitmap(q);d.regX=q.width/2;d.regY=q.height/2;d.x=CANVAS_WIDTH/2-220;d.y=CANVAS_HEIGHT/2+130;t.addChild(d);a.push(d);r=[];for(q=0;18>q;q++)r.push(s_oSpriteLibrary.getSprite("player_running_"+
q));n=this._attachPlayerRun();n.gotoAndPlay("anim");f=createBitmap(m);f.regX=m.width/2;f.regY=m.height/2;f.x=CANVAS_WIDTH/2+240;f.y=CANVAS_HEIGHT/2+130;t.addChild(f);a.push(f);r=[];for(q=0;26>q;q++)r.push(s_oSpriteLibrary.getSprite("player_jump_"+q));c=this._attachPlayerJump();c.on("animationend",this._onEndJump,this);b=new CGfxButton(CANVAS_WIDTH/2,CANVAS_HEIGHT/2,s_oSpriteLibrary.getSprite("but_next"),t);b.addEventListener(ON_MOUSE_UP,this._onStart,this);this._playAnims()};this.unload=function(){k.off("click",
e)};this.show=function(){t.alpha=0;t.visible=!0;createjs.Tween.get(t).to({alpha:1},500)};this.hide=function(){createjs.Tween.get(t).to({alpha:0},500,createjs.Ease.cubicOut).call(function(){clearInterval(g);t.visible=!1})};this._attachPlayerRun=function(){var m={images:[s_oSpriteLibrary.getSprite("player_running-0"),s_oSpriteLibrary.getSprite("player_running-1")],frames:[[1,1,404,403,0,-74,-45],[407,1,413,416,0,-68,-32],[822,1,421,429,0,-66,-19],[1245,1,420,440,0,-64,-8],[1,443,427,444,0,-58,-4],[430,
443,438,440,0,-53,-8],[870,443,447,432,0,-46,-16],[1319,443,454,416,0,-35,-32],[1,889,479,404,0,-22,-44],[482,889,507,407,0,-22,-41],[991,889,523,421,0,-39,-27],[1516,889,506,433,0,-65,-15],[1,1324,510,440,0,-74,-8],[513,1324,503,440,0,-75,-8],[1018,1324,475,436,0,-75,-12],[1495,1324,443,426,0,-75,-22],[1,1,421,410,1,-78,-38],[424,1,401,396,1,-83,-52]],animations:{start:0,anim:[0,17]}};m=new createjs.SpriteSheet(m);m=new createjs.Sprite(m,"start");m.scaleX=m.scaleY=.4;m.x=CANVAS_WIDTH/2-320;m.y=CANVAS_HEIGHT/
2+70;m.regX=304.5;m.regY=448;t.addChild(m);return m};this._attachPlayerJump=function(m,r){var q={images:[s_oSpriteLibrary.getSprite("player_jump-0"),s_oSpriteLibrary.getSprite("player_jump-1"),s_oSpriteLibrary.getSprite("player_jump-2")],frames:[[1,1,405,403,0,-266,-309],[408,1,415,457,0,-253,-255],[825,1,421,503,0,-243,-209],[1248,1,428,547,0,-227,-165],[1,550,438,581,0,-218,-131],[441,550,452,608,0,-213,-104],[895,550,481,632,0,-210,-80],[1378,550,545,655,0,-202,-57],[1,1207,589,678,0,-196,-34],
[592,1207,628,696,0,-197,-16],[1222,1207,663,705,0,-202,-7],[1,1,695,702,1,-207,-10],[698,1,724,693,1,-211,-19],[1,705,746,679,1,-215,-33],[749,705,761,660,1,-219,-52],[1,1386,767,638,1,-223,-74],[770,1386,754,614,1,-226,-98],[1,1,692,586,2,-232,-126],[695,1,644,556,2,-238,-156],[1341,1,588,525,2,-239,-187],[1,589,539,503,2,-238,-209],[542,589,518,489,2,-240,-223],[1062,589,488,472,2,-244,-240],[1552,589,447,452,2,-249,-260],[1,1094,420,429,2,-257,-283],[423,1094,404,403,2,-266,-309]],animations:{start:0,
anim:[0,25,"stop_anim"],stop_anim:25}};q=new createjs.SpriteSheet(q);q=new createjs.Sprite(q,"start");q.scaleX=q.scaleY=.4;q.x=CANVAS_WIDTH/2+180;q.y=CANVAS_HEIGHT/2-35;q.regX=304.5;q.regY=448;t.addChild(q);return q};this._playAnims=function(){var m=n.x+130,r=n.x;d.scaleX=d.scaleY=.9;createjs.Tween.get(n,{loop:!0}).to({x:m},2E3,createjs.Ease.cubicOut).call(function(){d.scaleX=d.scaleY=1;h.scaleX=h.scaleY=.9}).to({x:r},2E3,createjs.Ease.cubicOut).call(function(){h.scaleX=h.scaleY=1;d.scaleX=d.scaleY=
.9});g=setInterval(function(){f.scaleX=f.scaleY=.9;c.gotoAndPlay("anim")},3E3)};this._onEndJump=function(m){"anim"===m.currentTarget.currentAnimation&&(f.scaleX=f.scaleY=1)};this._onStart=function(){b.disable();u.hide();s_oGame.onExitFromHelp()};this._init()}
function CLevelSettings(){var a,g,e,k;this._init=function(){a=[16,20,22,24,26,28,30,30,32,34,36,38];g=[1500,1200,1E3,1200,1100,1E3,1E3,1200,1100,800,700,600];e=[1,1,1,2,2,2,2,3,3,2,2,2];k=[[4],[4],[5],[6],[7],[8],[9],[10],[11],[12],[4,9],[5,10]];NUM_LEVELS=a.length};this.getEnemiesSpawn=function(h){return a[h-1]};this.getStartingEnemySpawn=function(h){return g[h-1]};this.getEnemySpawnNumber=function(h){return e[h-1]};this.getPowerUps=function(h){return k[h-1]};this._init()}
function CLevelMenu(){var a,g,e,k,h,d,f,b,n,c,t,u,m,r,q,y,D,A,p,F=null,z=null;this._init=function(){f=0;A=new createjs.Container;s_oStage.addChild(A);var w=createBitmap(s_oSpriteLibrary.getSprite("bg_menu_level"));A.addChild(w);r=new createjs.Shape;r.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);r.alpha=.5;A.addChild(r);q=new createjs.Container;q.x=CANVAS_WIDTH/2;A.addChild(q);m=s_oSpriteLibrary.getSprite("msg_box_wide");w=createBitmap(m);q.addChild(w);new CTLText(q,0,0,m.width,
46,80,"center","#ffffff",FONT_GAME,1,20,2,TEXT_SELECT_LEVEL,!0,!0,!0,!1);w=s_oSpriteLibrary.getSprite("but_exit");h=CANVAS_WIDTH-w.width/2-10;d=w.height/2+10;y=new CGfxButton(h,d,w,s_oStage);y.addEventListener(ON_MOUSE_UP,this._onExit,this);q.regX=m.width/2;q.regY=m.height/2;b=-m.height/2;n=w.height;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)w=s_oSpriteLibrary.getSprite("audio_icon"),e=h-w.width/2-10,k=d,D=new CToggle(e,k,w,s_bAudioActive,s_oStage),D.addEventListener(ON_MOUSE_UP,this._onAudioToggle,
this);w=window.document;var v=w.documentElement;F=v.requestFullscreen||v.mozRequestFullScreen||v.webkitRequestFullScreen||v.msRequestFullscreen;z=w.exitFullscreen||w.mozCancelFullScreen||w.webkitExitFullscreen||w.msExitFullscreen;!1===ENABLE_FULLSCREEN&&(F=!1);F&&screenfull.isEnabled&&(w=s_oSpriteLibrary.getSprite("but_fullscreen"),a=w.width/4+10,g=w.height/2+10,p=new CToggle(a,g,w,s_bFullscreen,s_oStage),p.addEventListener(ON_MOUSE_UP,this._onFullscreenRelease,this));this._checkBoundLimits();t=[];
w=Math.floor((m.width-100)/NUM_COLS_PAGE_LEVEL)/2;for(var H=v=0;H<NUM_COLS_PAGE_LEVEL;H++)t.push(v),v+=2*w;u=[];this._createNewLevelPage(0,NUM_LEVELS);this.refreshButtonPos();r.alpha=0;q.y=b;A.visible=!0;createjs.Tween.get(r).to({alpha:.7},500);createjs.Tween.get(q).to({y:CANVAS_HEIGHT/2},1E3,createjs.Ease.bounceOut)};this.unload=function(){for(var w=0;w<c.length;w++)c[w].unload();!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||D.unload();F&&screenfull.isEnabled&&p.unload();y.unload();s_oStage.removeAllChildren();
s_oLevelMenu=null};this.refreshButtonPos=function(){y.setPosition(h-s_iOffsetX,d+s_iOffsetY);!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||D.setPosition(e-s_iOffsetX,s_iOffsetY+k);F&&screenfull.isEnabled&&p.setPosition(a+s_iOffsetX,g+s_iOffsetY)};this._checkBoundLimits=function(){for(var w=s_oSpriteLibrary.getSprite("but_level"),v=0,H=CANVAS_HEIGHT-2*EDGEBOARD_Y-2*n,x=0;v<H;)v+=w.height+20,x++;NUM_ROWS_PAGE_LEVEL>x&&(NUM_ROWS_PAGE_LEVEL=x);H=v=0;x=CANVAS_WIDTH-2*EDGEBOARD_X;for(w=s_oSpriteLibrary.getSprite("but_level");H<
x;)H+=w.width/2+5,v++;NUM_COLS_PAGE_LEVEL>v&&(NUM_COLS_PAGE_LEVEL=v)};this._createNewLevelPage=function(w,v){var H=new createjs.Container;q.addChild(H);u.push(H);c=[];for(var x=0,P=0,O=1,Q=!1,I=s_oSpriteLibrary.getSprite("but_level"),T=w;T<v;T++){var R=new CLevelBut(t[x]+I.width/4,P+I.height/2,T+1,I,T+1>s_iLastLevel?!1:!0,H);R.addEventListenerWithParams(ON_MOUSE_UP,this._onButLevelRelease,this,T);c.push(R);x++;if(x===t.length&&(x=0,P+=I.height+70,O++,O>NUM_ROWS_PAGE_LEVEL&&T!==v-1)){Q=!0;break}}H.x=
m.width/2;H.y=m.height/2;H.regX=H.getBounds().width/2;H.regY=H.getBounds().height/2;Q&&this._createNewLevelPage(T+1,v)};this._onRight=function(){u[f].visible=!1;f++;f>=u.length&&(f=0);u[f].visible=!0};this._onLeft=function(){u[f].visible=!1;f--;0>f&&(f=u.length-1);u[f].visible=!0};this._onButLevelRelease=function(w){s_oLevelMenu.unload();s_oMain.levelSelected(w+1)};this._onAudioToggle=function(){Howler.mute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this.resetFullscreenBut=function(){F&&screenfull.isEnabled&&
p.setActive(s_bFullscreen)};this._onFullscreenRelease=function(){s_bFullscreen?z.call(window.document):F.call(window.document.documentElement);sizeHandler()};this._onExit=function(){s_oLevelMenu.unload();s_oMain.gotoMenu()};s_oLevelMenu=this;this._init()}var s_oLevelMenu=null;
function CLevelBut(a,g,e,k,h,d){var f,b,n,c=[],t=[],u,m,r,q;this._init=function(D,A,p,F,z){b=[];n=[];q=new createjs.Container;y.addChild(q);var w=new createjs.SpriteSheet({images:[F],frames:{width:F.width/2,height:F.height,regX:F.width/2/2,regY:F.height/2},animations:{state_true:[0],state_false:[1]}});f=z;r=createSprite(w,"state_"+f,F.width/2/2,F.height/2,F.width/2,F.height);r.mouseEnabled=z;r.x=D;r.y=A;r.stop();s_bMobile||(q.cursor="pointer");q.addChild(r);c.push(r);u=new createjs.Text(p,"60px "+
FONT_GAME,"#00397a");u.x=D;u.y=A+10;u.textAlign="center";u.textBaseline="alphabetic";u.lineWidth=200;u.outline=6;q.addChild(u);m=new createjs.Text(p,"60px "+FONT_GAME,"#fff");m.x=D;m.y=A+10;m.textAlign="center";m.textBaseline="alphabetic";m.lineWidth=200;q.addChild(m);z||(m.color="#b4b4b4",u.color="#0264d3");this._initListener()};this.unload=function(){q.off("mousedown",this.buttonDown);q.off("pressup",this.buttonRelease);q.removeChild(r)};this._initListener=function(){q.on("mousedown",this.buttonDown);
q.on("pressup",this.buttonRelease)};this.viewBut=function(D){q.addChild(D)};this.addEventListener=function(D,A,p){b[D]=A;n[D]=p};this.addEventListenerWithParams=function(D,A,p,F){b[D]=A;n[D]=p;t=F};this.ifClickable=function(){return!0===q.mouseEnabled?1:0};this.setActive=function(D,A){f=A;c[D].gotoAndStop("state_"+f);c[D].mouseEnabled=!0;f?(m.color="#00397a",u.color="#fff"):(m.color="#b4b4b4",u.color="#0264d3")};this.buttonRelease=function(){f&&(playSound("click",1,!1),b[ON_MOUSE_UP]&&b[ON_MOUSE_UP].call(n[ON_MOUSE_UP],
t))};this.buttonDown=function(){b[ON_MOUSE_DOWN]&&b[ON_MOUSE_DOWN].call(n[ON_MOUSE_DOWN],t)};this.setPosition=function(D,A){q.x=D;q.y=A};this.setVisible=function(D){q.visible=D};var y=d;this._init(a,g,e,k,h,d)}
function CCreditsPanel(){var a,g,e,k,h,d,f;this._init=function(){f=new createjs.Container;s_oStage.addChild(f);var b=new createjs.Shape;b.graphics.beginFill("rgba(0,0,0,0.7)").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);f.addChild(b);b=s_oSpriteLibrary.getSprite("msg_box");a=createBitmap(b);a.regX=b.width/2;a.regY=b.height/2;a.x=CANVAS_WIDTH/2;a.y=CANVAS_HEIGHT/2;f.addChild(a);h=new createjs.Shape;h.graphics.beginFill("#0f0f0f").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);h.alpha=.01;h.on("click",this._onLogoButRelease);
f.addChild(h);b=s_oSpriteLibrary.getSprite("but_exit");e=new CGfxButton(980,240,b,f);e.addEventListener(ON_MOUSE_UP,this.unload,this);k=new createjs.Text(TEXT_CREDITS_DEVELOPED,"26px "+FONT_GAME,"#fff");k.textAlign="center";k.textBaseline="alphabetic";k.x=CANVAS_WIDTH/2;k.y=330;f.addChild(k);b=s_oSpriteLibrary.getSprite("logo_ctl");g=createBitmap(b);g.regX=b.width/2;g.regY=b.height/2;g.x=CANVAS_WIDTH/2;g.y=CANVAS_HEIGHT/2;f.addChild(g);d=new createjs.Text("www.codethislab.com","16px "+FONT_GAME,"#fff");
d.textAlign="center";d.textBaseline="alphabetic";d.x=CANVAS_WIDTH/2;d.y=510;f.addChild(d)};this.unload=function(){h.off("click",this._onLogoButRelease);e.unload();e=null;s_oStage.removeChild(f)};this._onLogoButRelease=function(){window.open("https://www.codethislab.com/","_blank")};this._init()}
function CAlertSavingBox(a,g){var e,k;this._init=function(f){k=new createjs.Container;d.addChild(k);var b=new createjs.Shape;b.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);b.alpha=.5;b.on("click",function(){});k.addChild(b);b=s_oSpriteLibrary.getSprite("msg_box");var n=createBitmap(b);n.x=.5*CANVAS_WIDTH;n.y=.5*CANVAS_HEIGHT;n.regX=.5*b.width;n.regY=.5*b.height;k.addChild(n);new CTLText(k,CANVAS_WIDTH/2-b.width/2,CANVAS_HEIGHT/2-140,b.width,190,40,"center","#ffffff",FONT_GAME,
1,20,10,f,!0,!0,!0,!1);e=new CGfxButton(CANVAS_WIDTH/2,475,s_oSpriteLibrary.getSprite("but_exit"),k);e.addEventListener(ON_MOUSE_UP,this._onButOk,this)};this._onButOk=function(){h.unload()};this.unload=function(){e.unload();d.removeChild(k)};var h=this;var d=g;this._init(a)}
function CAreYouSurePanel(){var a,g,e,k,h,d,f,b,n=this;this._init=function(){a=[];g=[];f=new createjs.Container;f.visible=!1;s_oStage.addChild(f);b=new createjs.Shape;b.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);b.alpha=.5;b.on("click",function(){});f.addChild(b);var c=s_oSpriteLibrary.getSprite("msg_box");e=createBitmap(c);e.x=CANVAS_WIDTH/2;e.y=CANVAS_HEIGHT/2;e.regX=.5*c.width;e.regY=.5*c.height;f.addChild(e);k=new CTLText(f,CANVAS_WIDTH/2-c.width/2,CANVAS_HEIGHT/2-c.height/
2,c.width,150,70,"center","#ffffff",FONT_GAME,1,40,10,TEXT_ARE_SURE,!0,!0,!0,!1);h=new CGfxButton(CANVAS_WIDTH/2+150,.5*CANVAS_HEIGHT+70,s_oSpriteLibrary.getSprite("but_yes"),f);h.addEventListener(ON_MOUSE_UP,this._onButYes,this);d=new CGfxButton(CANVAS_WIDTH/2-150,.5*CANVAS_HEIGHT+70,s_oSpriteLibrary.getSprite("but_no"),f);d.addEventListener(ON_MOUSE_UP,this._onButNo,this)};this.addEventListener=function(c,t,u){a[c]=t;g[c]=u};this.show=function(c){k.refreshText(c);f.alpha=0;f.visible=!0;createjs.Tween.get(f).to({alpha:1},
300,createjs.Ease.quartOut).call(function(){s_oMain.stopUpdateNoBlock()})};this.hide=function(){s_oMain.startUpdateNoBlock();createjs.Tween.get(f).to({alpha:0},500,createjs.Ease.quartOut).call(function(){f.visible=!1})};this.unload=function(){d.unload();h.unload()};this._onButYes=function(){n.hide();a[ON_BUT_YES_DOWN]&&a[ON_BUT_YES_DOWN].call(g[ON_BUT_YES_DOWN])};this._onButNo=function(){n.hide()};this._init()}
function CGUIExpandible(a,g,e,k){var h,d,f,b,n,c,t,u;this._init=function(r,q,y,D){b=[];c=new createjs.Container;c.x=r;c.y=q;D.addChild(c);t=new createjs.Container;c.addChild(t);u=new createjs.Container;c.addChild(u);f=!1;n=new CGfxButton(0,0,y,u);n.addEventListener(ON_MOUSE_UP,this._onMenu,this);d=h=85};this.unload=function(){n.unload();k.removeChild(c)};this.refreshPos=function(){c.x=a-s_iOffsetX;c.y=g+s_iOffsetY};this.addButton=function(r){r=r.getButtonImage();r.x=0;r.y=0;r.visible=0;t.addChildAt(r,
0);b.push(r)};this._onMenu=function(){(f=!f)?m._expand():m._collapse()};this._expand=function(){for(var r=0;r<b.length;r++)b[r].visible=!0,createjs.Tween.get(b[r],{override:!0}).wait(300*r/2).to({y:h+r*d},300,createjs.Ease.cubicOut)};this._collapse=function(){for(var r=0;r<b.length;r++){var q=b[b.length-1-r];createjs.Tween.get(q,{override:!0}).wait(300*r/2).to({y:0},300,createjs.Ease.cubicOut).call(function(y){y.visible=!1},[q])}};var m=this;this._init(a,g,e,k)}
function CField(a,g,e){var k=!1,h,d,f,b;this._init=function(c,t){b=new createjs.Container;b.visible=!1;b.x=c;b.y=t;n.addChild(b);f=[];for(var u=0;18>u;u++){var m=createBitmap(s_oSpriteLibrary.getSprite("field_loop_"+u));b.addChild(m);f.push(m);0<u&&(m.visible=!1)}};this.show=function(){h=f.length;f[0].visible=!0;d=0;k=b.visible=!0};this.hide=function(){b.visible=!1};this.playToFrame=function(c){f[d].visible=!1;d=c;f[d].visible=!0};this.nextFrame=function(){f[d].visible=!1;d++;f[d].visible=!0};this.update=
function(){!1!==k&&(d===h-1?this.playToFrame(0):this.nextFrame())};var n=e;this._init(a,g)}
function CFieldEndZone(a,g,e){var k=!1,h,d,f,b;this._init=function(c,t){b=new createjs.Container;b.visible=!1;b.x=c;b.y=t;n.addChild(b);f=[];for(var u=0;39>u;u++){var m=createBitmap(s_oSpriteLibrary.getSprite("end_zone_"+u));b.addChild(m);f.push(m);0<u&&(m.visible=!1)}};this.show=function(){h=f.length;f[0].visible=!0;d=0;k=b.visible=!0};this.hide=function(){b.visible=!1};this.reset=function(){for(var c=0;c<f.length;c++)f[c].visible=!1;b.visible=!1};this.playToFrame=function(c){f[d].visible=!1;d=c;
f[d].visible=!0};this.nextFrame=function(){f[d].visible=!1;d++;f[d].visible=!0};this.update=function(){!1!==k&&(d===h-1?(k=!1,s_oGame.endZonePlayed()):this.nextFrame())};var n=e;this._init(a,g)}
function CPlayer(a,g,e){var k=!1,h,d=!1,f=!1,b,n,c,t,u,m,r,q,y,D,A,p,F=this,z;this._init=function(v,H){h=!1;n=v;c=H;m=0;t=HERO_ACCELERATION;u=MAX_HERO_SPEED;A=[];p=[];z=new createjs.Container;z.x=v;z.y=H;w.addChild(z);y=[];D=[];D[PLAYER_ANIM_RUN]=18;D[PLAYER_ANIM_FALL]=9;D[PLAYER_ANIM_TOUCHDOWN]=50;D[PLAYER_ANIM_JUMP]=26;var x={images:[s_oSpriteLibrary.getSprite("player_running-0"),s_oSpriteLibrary.getSprite("player_running-1")],frames:[[1,1,404,403,0,-74,-45],[407,1,413,416,0,-68,-32],[822,1,421,
429,0,-66,-19],[1245,1,420,440,0,-64,-8],[1,443,427,444,0,-58,-4],[430,443,438,440,0,-53,-8],[870,443,447,432,0,-46,-16],[1319,443,454,416,0,-35,-32],[1,889,479,404,0,-22,-44],[482,889,507,407,0,-22,-41],[991,889,523,421,0,-39,-27],[1516,889,506,433,0,-65,-15],[1,1324,510,440,0,-74,-8],[513,1324,503,440,0,-75,-8],[1018,1324,475,436,0,-75,-12],[1495,1324,443,426,0,-75,-22],[1,1,421,410,1,-78,-38],[424,1,401,396,1,-83,-52]],animations:{start:0,anim:[0,D[PLAYER_ANIM_RUN]-1]}};x=new createjs.SpriteSheet(x);
y[PLAYER_ANIM_RUN]=new createjs.Sprite(x,"start");y[PLAYER_ANIM_RUN].regX=304.5;y[PLAYER_ANIM_RUN].regY=448;z.addChild(y[PLAYER_ANIM_RUN]);x={images:[s_oSpriteLibrary.getSprite("player_falling")],frames:[[1,1,404,403,0,-74,-45],[407,1,404,403,0,-74,-45],[813,1,424,403,0,-63,-45],[1239,1,449,400,0,-50,-48],[1,406,477,377,0,-36,-71],[480,406,550,309,0,-16,-139],[1032,406,550,309,0,-16,-139],[1,785,582,248,0,-4,-200],[585,785,596,88,0,-7,-360]],animations:{start:0,anim:[0,D[PLAYER_ANIM_FALL]-1,"stop_anim"],
stop_anim:D[PLAYER_ANIM_FALL]}};x=new createjs.SpriteSheet(x);y[PLAYER_ANIM_FALL]=new createjs.Sprite(x,"start");y[PLAYER_ANIM_FALL].on("animationend",this._onPlayerFall,this);y[PLAYER_ANIM_FALL].visible=!1;y[PLAYER_ANIM_FALL].regX=304.5;y[PLAYER_ANIM_FALL].regY=448;z.addChild(y[PLAYER_ANIM_FALL]);x={images:[s_oSpriteLibrary.getSprite("player_touchdown-0"),s_oSpriteLibrary.getSprite("player_touchdown-1")],frames:[[1,1,401,396,0,-83,-52],[404,1,385,386,0,-95,-62],[791,1,361,370,0,-113,-78],[1154,1,
343,357,0,-128,-91],[1499,1,322,362,0,-135,-86],[1,399,304,370,0,-138,-78],[307,399,296,377,0,-142,-71],[605,399,289,384,0,-145,-64],[896,399,281,383,0,-149,-65],[1179,399,277,383,0,-150,-65],[1458,399,273,381,0,-152,-67],[1733,399,269,378,0,-157,-70],[1,785,260,377,0,-172,-71],[263,785,241,375,0,-192,-73],[506,785,218,374,0,-202,-74],[726,785,197,376,0,-204,-72],[925,785,215,378,0,-201,-70],[1142,785,223,380,0,-194,-68],[1367,785,230,381,0,-184,-67],[1599,785,238,383,0,-182,-65],[1,1170,261,383,
0,-183,-65],[264,1170,279,383,0,-185,-65],[545,1170,286,382,0,-188,-66],[833,1170,294,379,0,-195,-69],[1129,1170,291,376,0,-201,-72],[1422,1170,275,373,0,-210,-75],[1699,1170,259,368,0,-215,-80],[1,1555,241,363,0,-218,-84],[244,1555,236,353,0,-210,-86],[482,1555,251,345,0,-189,-89],[735,1555,283,335,0,-154,-92],[1020,1555,307,326,0,-131,-94],[1329,1555,301,315,0,-137,-97],[1632,1555,287,318,0,-149,-89],[1,1,289,283,1,-148,-120],[292,1,282,259,1,-157,-142],[576,1,259,234,1,-188,-166],[1,286,244,211,
1,-213,-185],[247,286,237,195,1,-229,-199],[486,286,229,178,1,-242,-210],[717,286,224,161,1,-246,-221],[1,499,231,154,1,-253,-229],[234,499,241,145,1,-260,-237],[477,499,241,153,1,-264,-228],[720,499,223,154,1,-270,-226],[1,655,190,156,1,-277,-224],[193,655,184,155,1,-266,-224],[379,655,184,155,1,-268,-223],[565,655,181,157,1,-275,-221],[748,655,183,161,1,-275,-216],[1,818,188,169,1,-275,-207],[191,818,192,180,1,-273,-196],[385,818,196,188,1,-273,-188],[583,818,199,193,1,-273,-183],[784,818,203,199,
1,-272,-177],[1,1019,207,204,1,-271,-172],[210,1019,208,207,1,-270,-169],[420,1019,207,206,1,-271,-170],[629,1019,219,202,1,-269,-174],[1,1228,240,193,1,-269,-183],[243,1228,258,181,1,-268,-195],[503,1228,274,168,1,-268,-208],[1,1423,294,145,1,-268,-231],[297,1423,315,134,1,-267,-242],[614,1423,328,136,1,-267,-240],[1,1570,333,136,1,-266,-240],[336,1570,334,128,1,-265,-248],[672,1570,328,114,1,-265,-262]],animations:{start:0,anim:[0,D[PLAYER_ANIM_TOUCHDOWN]-1,"stop_anim"],stop_anim:D[PLAYER_ANIM_TOUCHDOWN]-
1}};x=new createjs.SpriteSheet(x);y[PLAYER_ANIM_TOUCHDOWN]=new createjs.Sprite(x,"start");y[PLAYER_ANIM_TOUCHDOWN].on("animationend",this._onPlayerTouchdown,this);y[PLAYER_ANIM_TOUCHDOWN].visible=!1;y[PLAYER_ANIM_TOUCHDOWN].regX=304.5;y[PLAYER_ANIM_TOUCHDOWN].regY=448;z.addChild(y[PLAYER_ANIM_TOUCHDOWN]);x={images:[s_oSpriteLibrary.getSprite("player_jump-0"),s_oSpriteLibrary.getSprite("player_jump-1"),s_oSpriteLibrary.getSprite("player_jump-2")],frames:[[1,1,405,403,0,-266,-309],[408,1,415,457,0,
-253,-255],[825,1,421,503,0,-243,-209],[1248,1,428,547,0,-227,-165],[1,550,438,581,0,-218,-131],[441,550,452,608,0,-213,-104],[895,550,481,632,0,-210,-80],[1378,550,545,655,0,-202,-57],[1,1207,589,678,0,-196,-34],[592,1207,628,696,0,-197,-16],[1222,1207,663,705,0,-202,-7],[1,1,695,702,1,-207,-10],[698,1,724,693,1,-211,-19],[1,705,746,679,1,-215,-33],[749,705,761,660,1,-219,-52],[1,1386,767,638,1,-223,-74],[770,1386,754,614,1,-226,-98],[1,1,692,586,2,-232,-126],[695,1,644,556,2,-238,-156],[1341,1,
588,525,2,-239,-187],[1,589,539,503,2,-238,-209],[542,589,518,489,2,-240,-223],[1062,589,488,472,2,-244,-240],[1552,589,447,452,2,-249,-260],[1,1094,420,429,2,-257,-283],[423,1094,404,403,2,-266,-309]],animations:{start:0,anim:[0,D[PLAYER_ANIM_JUMP]-1,"stop_anim"],stop_anim:D[PLAYER_ANIM_JUMP]}};x=new createjs.SpriteSheet(x);y[PLAYER_ANIM_JUMP]=new createjs.Sprite(x,"start");y[PLAYER_ANIM_JUMP].on("animationend",this._onPlayerJump);y[PLAYER_ANIM_JUMP].visible=!1;y[PLAYER_ANIM_JUMP].x=-200;y[PLAYER_ANIM_JUMP].y=
-220;y[PLAYER_ANIM_JUMP].regX=304.5;y[PLAYER_ANIM_JUMP].regY=448;z.addChild(y[PLAYER_ANIM_JUMP]);b=PLAYER_ANIM_RUN};this.addEventListener=function(v,H,x){A[v]=H;p[v]=x};this.show=function(){y[b].visible=!0;y[b].gotoAndPlay("anim");z.visible=!0;r=z.getBounds().width-200;q=z.getBounds().height;k=!0};this.hide=function(){k=!1;z.visible=!1};this.reset=function(){f=d=h=k=!1;m=0;t=HERO_ACCELERATION;u=MAX_HERO_SPEED;z.alpha=1;z.x=n;z.y=c;y[PLAYER_ANIM_RUN].visible=!1;y[PLAYER_ANIM_FALL].visible=!1;y[PLAYER_ANIM_TOUCHDOWN].visible=
!1;y[PLAYER_ANIM_JUMP].visible=!1;b=PLAYER_ANIM_RUN};this.changeAnim=function(v){y[b].visible=!1;y[b].gotoAndStop("start");b=v;y[b].visible=!0;y[b].gotoAndPlay("anim")};this.jump=function(){h=!0;this.changeAnim(PLAYER_ANIM_JUMP)};this.moveLeft=function(v){d=v};this.moveRight=function(v){f=v};this.setAcceleration=function(v,H){t=v;u=H};this.setY=function(v){z.y=v};this._onPlayerFall=function(v){"anim"===v.currentTarget.currentAnimation&&(F.hide(),A[ON_PLAYER_TACKLED]&&A[ON_PLAYER_TACKLED].call(p[ON_PLAYER_TACKLED]))};
this._onPlayerTouchdown=function(v){"anim"===v.currentTarget.currentAnimation&&((new createjs.Tween.get(z)).to({alpha:0},500),A[ON_PLAYER_TOUCHDOWN]&&A[ON_PLAYER_TOUCHDOWN].call(p[ON_PLAYER_TOUCHDOWN]))};this._onPlayerJump=function(v){"anim"===v.currentTarget.currentAnimation&&(h=!1,F.changeAnim(PLAYER_ANIM_RUN))};this.getRect=function(){return new createjs.Rectangle(z.x-r/2,z.y-q,r,q)};this.isJumping=function(){return h};this.getCurAnim=function(){return b};this.getX=function(){return z.x};this._updateMove=
function(){b===PLAYER_ANIM_RUN&&(d&&(m-=t),f&&(m+=t),z.x+=m,m*=HERO_FRICTION,m>u&&(m=u),m<-u&&(m=-u),.1>Math.abs(m)&&(m=0),z.x+m>CANVAS_WIDTH-s_iOffsetX&&(z.x=CANVAS_WIDTH-m-s_iOffsetX),z.x-m<s_iOffsetX&&(z.x=m+s_iOffsetX))};this.update=function(){!1!==k&&this._updateMove()};var w=e;this._init(a,g)}
function COpponent(a,g,e,k){var h,d,f=!1,b,n,c,t,u,m,r,q,y,D,A,p=this;this._init=function(z,w){y=[];D=[];h=z;d=w;A=new createjs.Container;A.x=z;A.y=w;A.scaleX=A.scaleY=.1;F.addChild(A);q=[];q[PLAYER_ANIM_RUN]=18;q[PLAYER_ANIM_FALL]=18;r=[];r[PLAYER_ANIM_RUN]=[];for(var v=0;v<q[PLAYER_ANIM_RUN];v++){var H=s_oSpriteLibrary.getSprite("enemy_running_"+v),x=createBitmap(H);x.visible=!1;x.regX=H.width/2;x.regY=H.height;A.addChild(x);r[PLAYER_ANIM_RUN].push(x);u=H.width-500;m=H.height}r[PLAYER_ANIM_FALL]=
[];for(v=0;v<q[PLAYER_ANIM_FALL];v++)H=s_oSpriteLibrary.getSprite("enemy_tackle_"+v),x=createBitmap(H),x.visible=!1,x.regX=H.width/2,x.regY=H.height,A.addChild(x),r[PLAYER_ANIM_FALL].push(x);b=PLAYER_ANIM_RUN;this.show()};this.addEventListener=function(z,w,v){y[z]=w;D[z]=v};this.reset=function(){A.x=h;A.y=d;A.scaleX=A.scaleY=.1;for(var z=0;z<q[PLAYER_ANIM_RUN];z++)r[PLAYER_ANIM_RUN][z].visible=!1;for(z=0;z<q[PLAYER_ANIM_FALL];z++)r[PLAYER_ANIM_FALL][z].visible=!1;b=PLAYER_ANIM_RUN};this.show=function(){f=
!1;n=1;this.reset();p._startRun()};this._startRun=function(){c=q[b];r[b][0].visible=!0;t=Math.floor(Math.random()*r[PLAYER_ANIM_RUN].length);A.alpha=0;A.visible=!0;(new createjs.Tween.get(A)).to({alpha:1},500);(new createjs.Tween.get(A)).to({scaleX:1,scaleY:1,y:OPPONENT_FINAL_Y},TIME_OPPONENT_RUN,createjs.Ease.cubicIn).call(function(){if(y[ON_OPPONENT_TACKLE]){var z=new createjs.Rectangle(A.x-u/2,A.y-m,u,m);y[ON_OPPONENT_TACKLE].call(D[ON_OPPONENT_TACKLE],z)}});(new createjs.Tween.get(A)).wait(2500).call(function(){s_oGame.getPlayerX()>
A.x&&(n=-1);p._changeAnim(PLAYER_ANIM_FALL,Math.floor(4*Math.random()));playSound("enemy",1,!1)});setTimeout(function(){},2500);f=!0};this.hide=function(){f=!1;A.visible=!1;y[ON_OPPONENT_HIDE]&&y[ON_OPPONENT_HIDE].call(D[ON_OPPONENT_HIDE],a)};this.playToFrame=function(z){r[b][t].visible=!1;t=z;r[b][t].scaleX=n;r[b][t].visible=!0};this.nextFrame=function(){r[b][t].visible=!1;t++;r[b][t].scaleX=n;r[b][t].visible=!0};this._changeAnim=function(z,w){f=!1;r[b][t].visible=!1;b=z;t=w;r[b][t].visible=!0;c=
q[b];f=!0};this.update=function(){!1!==f&&(t===c-1?b===PLAYER_ANIM_RUN?this.playToFrame(0):this.hide():this.nextFrame())};var F=k;this._init(g,e)}
function CEndPanel(){var a,g,e,k,h,d,f,b,n,c,t,u,m=this;this._init=function(){e=[];k=[];t=new createjs.Container;t.visible=!1;s_oStage.addChild(t);d=new createjs.Shape;d.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);d.alpha=0;h=d.on("click",function(){});t.addChild(d);u=new createjs.Container;u.x=CANVAS_WIDTH/2;t.addChild(u);var r=s_oSpriteLibrary.getSprite("msg_box_wide"),q=createBitmap(r);u.addChild(q);f=new CTLText(u,0,0,r.width,120,80,"center","#ffffff",FONT_GAME,1,40,10,
"",!0,!0,!0,!1);b=new CTLText(u,0,r.height/2-60,r.width,80,80,"center","#ffffff",FONT_GAME,1,40,10,"",!0,!0,!0,!1);n=new CGfxButton(r.width/2-250,r.height/2+120,s_oSpriteLibrary.getSprite("but_home"),u);n.addEventListener(ON_MOUSE_UP,this._onHome,this);c=new CGfxButton(r.width/2+250,r.height/2+120,s_oSpriteLibrary.getSprite("but_restart"),u);c.addEventListener(ON_MOUSE_UP,this._onRestart,this);a=-r.height/2;u.regX=r.width/2;u.regY=r.height/2};this.unload=function(){n.unload();c.unload();d.off("click",
h)};this.addEventListener=function(r,q,y){e[r]=q;k[r]=y};this.show=function(r,q){setVolume("soundtrack",0);var y=q===TEXT_CONGRATS?playSound("level_win",1,!1):playSound("game_over",1,!1);if(null!==y)y.on("end",function(){setVolume("soundtrack",1)});f.refreshText(q);b.refreshText(TEXT_SCORE+": "+r);d.alpha=0;u.y=a;t.visible=!0;createjs.Tween.get(d).to({alpha:.7},500);createjs.Tween.get(u).wait(400).to({y:CANVAS_HEIGHT/2},1E3,createjs.Ease.bounceOut).call(function(){m.enableButtons()})};this.hide=function(){createjs.Tween.get(u).to({y:a},
1E3,createjs.Ease.backIn).call(function(){t.visible=!1;e[g]&&e[g].call(k[g])})};this.enableButtons=function(){n.enable();c.enable()};this.disableButtons=function(){n.disable();c.disable()};this._onHome=function(){m.disableButtons();g=ON_BACK_MENU;m.hide()};this._onRestart=function(){m.disableButtons();document.dispatchEvent(new CustomEvent("show_interlevel_ad"));g=ON_RESTART;m.hide()};this._init()}
function CPowerUp(a,g,e,k){var h,d,f,b;this._init=function(n,c,t){h=t;d=[];f=[];b=new createjs.Container;b.scaleX=b.scaleY=.1;b.x=n;b.y=c;k.addChild(b);c={images:[s_oSpriteLibrary.getSprite("power_up_"+h)],framerate:15,frames:{width:286,height:404},animations:{start:0,anim:[0,14]}};c=new createjs.SpriteSheet(c);c=createSprite(c,"anim",0,0,286,404);b.addChild(c);b.regX=143;b.regY=202;b.alpha=0;var u=(n-MIN_POWERUP_X)/(MAX_POWERUP_X-MIN_POWERUP_X)*1140;(new createjs.Tween.get(b)).to({alpha:1},500);
(new createjs.Tween.get(b)).to({scaleX:1,scaleY:1,x:u,y:POWERUP_FINAL_Y},1.5*TIME_OPPONENT_RUN,createjs.Ease.cubicIn).call(function(){if(d[ON_POWERUP_END_MOVE]){var m=new createjs.Rectangle(u-143,POWERUP_FINAL_Y-202,286,404);d[ON_POWERUP_END_MOVE].call(f[ON_POWERUP_END_MOVE],m,h);k.removeChild(b)}})};this.unload=function(){k.removeChild(b)};this.addEventListener=function(n,c,t){d[n]=c;f[n]=t};this.stopTween=function(){createjs.Tween.removeTweens(b)};this._init(a,g,e)}
function CNextLevelPanel(){var a,g,e,k,h,d,f,b,n,c,t,u,m,r,q=this;this._init=function(){e=[];k=[];m=new createjs.Container;m.visible=!1;s_oStage.addChild(m);d=new createjs.Shape;d.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);d.alpha=0;h=d.on("click",function(){});m.addChild(d);r=new createjs.Container;r.x=CANVAS_WIDTH/2;m.addChild(r);var y=s_oSpriteLibrary.getSprite("msg_box_wide"),D=createBitmap(y);r.addChild(D);b=new CTLText(r,0,0,y.width,120,80,"center","#ffffff",FONT_GAME,
1,40,10,"",!0,!0,!0,!1);f=new CTLText(r,0,y.height/2-70,y.width,60,80,"center","#ffffff",FONT_GAME,1,40,10,"",!0,!0,!0,!1);n=new CTLText(r,0,y.height/2,y.width,60,80,"center","#ffffff",FONT_GAME,1,40,10,"",!0,!0,!0,!1);c=new CGfxButton(y.width/2-250,y.height/2+120,s_oSpriteLibrary.getSprite("but_home"),r);c.addEventListener(ON_MOUSE_UP,this._onHome,this);t=new CGfxButton(y.width/2,y.height/2+120,s_oSpriteLibrary.getSprite("but_restart"),r);t.addEventListener(ON_MOUSE_UP,this._onRestart,this);u=new CGfxButton(y.width/
2+250,y.height/2+120,s_oSpriteLibrary.getSprite("but_next"),r);u.addEventListener(ON_MOUSE_UP,this._onNext,this);a=-y.height/2;r.regX=y.width/2;r.regY=y.height/2};this.unload=function(){c.unload();t.unload();d.off("click",h)};this.addEventListener=function(y,D,A){e[y]=D;k[y]=A};this.show=function(y,D,A){setVolume("soundtrack",0);var p=playSound("level_win",1,!1);if(null!==p)p.on("end",function(){setVolume("soundtrack",1)});b.refreshText(sprintf(TEXT_LEVEL_CLEARED,A));f.refreshText(TEXT_LEVEL_SCORE+
": "+y);n.refreshText(TEXT_SCORE+": "+D);d.alpha=0;r.y=a;m.visible=!0;createjs.Tween.get(d).to({alpha:.7},500);createjs.Tween.get(r).wait(400).to({y:CANVAS_HEIGHT/2},1E3,createjs.Ease.bounceOut).call(function(){q.enableButtons()})};this.hide=function(){createjs.Tween.get(r).to({y:a},1E3,createjs.Ease.backIn).call(function(){m.visible=!1;e[g]&&e[g].call(k[g])})};this.enableButtons=function(){c.enable();u.enable();t.enable()};this.disableButtons=function(){c.disable();u.disable();t.disable()};this._onHome=
function(){q.disableButtons();g=ON_BACK_MENU;q.hide()};this._onRestart=function(){q.disableButtons();document.dispatchEvent(new CustomEvent("show_interlevel_ad"));g=ON_RESTART;q.hide()};this._onNext=function(){q.disableButtons();document.dispatchEvent(new CustomEvent("show_interlevel_ad"));g=ON_NEXT_LEVEL;q.hide()};this._init()}var MS_ROLLING_SCORE=400;
function CRollingScore(){var a=null,g=null;this.rolling=function(e,k,h){a=createjs.Tween.get(e).to({text:h},MS_ROLLING_SCORE,createjs.Ease.cubicOut).call(function(){createjs.Tween.removeTweens(a);e.color="#fff"}).addEventListener("change",function(){e.text=Math.floor(e.text)});null!==k&&(g=createjs.Tween.get(k).to({text:h},MS_ROLLING_SCORE,createjs.Ease.cubicOut).call(function(){createjs.Tween.removeTweens(g)}).addEventListener("change",function(){k.text=Math.floor(k.text)}))};return this}
function CScoreText(a,g,e,k){var h;this._init=function(d,f,b){h=new createjs.Text("+"+d," 80px "+FONT_GAME,"#fff");h.textAlign="center";h.x=f;h.y=b;h.alpha=0;h.shadow=new createjs.Shadow("#000",1,1,1);k.addChild(h);var n=this;createjs.Tween.get(h).to({alpha:1},200,createjs.Ease.quadIn).call(function(){n.moveUp()})};this.moveUp=function(){var d=h.y-400,f=this;createjs.Tween.get(h).to({y:d},1500,createjs.Ease.sineIn).call(function(){f.unload()});createjs.Tween.get(h).wait(800).to({alpha:0},500)};this.unload=
function(){k.removeChild(h)};this._init(a,g,e)}
function CPowerUpGui(a){var g,e,k,h,d,f,b;this._init=function(){var n=s_oSpriteLibrary.getSprite("powerup_gui_off");k=n.width;h=n.height;g=CANVAS_WIDTH-n.width-10;e=CANVAS_HEIGHT-n.height-10;b=new createjs.Container;b.x=g;b.y=e;b.visible=!1;a.addChild(b);var c=createBitmap(n);b.addChild(c);c=createBitmap(s_oSpriteLibrary.getSprite("powerup_gui_on"));b.addChild(c);f=new createjs.Shape;f.graphics.beginFill("rgba(0,0,0,0.01)").drawRect(0,0,n.width,n.height);b.addChild(f);c.mask=f;d=new createjs.Text("00:00",
"20px "+FONT_GAME,"#fff");d.x=n.width/2;d.y=-10;d.textBaseline="alphabetic";d.textAlign="center";b.addChild(d)};this.refreshButtonPos=function(){b.x=g-s_iOffsetX;b.y=e-s_iOffsetY};this.reset=function(){b.visible=!1};this.show=function(){this.refreshTime(0);b.x+=k+10;b.visible=!0;createjs.Tween.get(b).to({x:g-s_iOffsetX},1E3,createjs.Ease.backOut)};this.hide=function(){createjs.Tween.get(b).to({x:b.x+k+10},1E3,createjs.Ease.backIn).call(function(){b.visible=!1})};this.refreshTime=function(n){d.text=
formatTime(TIME_EFFECT_POWERUP-n);f.graphics.clear();n=Math.floor((100-Math.floor(n/TIME_EFFECT_POWERUP*100))*k/100);f.graphics.beginFill("rgba(0,0,0,0.01)").drawRect(0,0,n,h)};this._init()}
CTLText.prototype={constructor:CTLText,__autofit:function(){if(this._bFitText){for(var a=this._iFontSize;(this._oText.getBounds().height>this._iHeight-2*this._iPaddingV||this._oText.getBounds().width>this._iWidth-2*this._iPaddingH)&&!(a--,this._oText.font=a+"px "+this._szFont,this._oText.lineHeight=Math.round(a*this._fLineHeightFactor),this.__updateY(),this.__verticalAlign(),8>a););this._iFontSize=a}},__verticalAlign:function(){if(this._bVerticalAlign){var a=this._oText.getBounds().height;this._oText.y-=
(a-this._iHeight)/2+this._iPaddingV}},__updateY:function(){this._oText.y=this._y+this._iPaddingV;switch(this._oText.textBaseline){case "middle":this._oText.y+=this._oText.lineHeight/2+(this._iFontSize*this._fLineHeightFactor-this._iFontSize)}},__createText:function(a){this._bDebug&&(this._oDebugShape=new createjs.Shape,this._oDebugShape.graphics.beginFill("rgba(255,0,0,0.5)").drawRect(this._x,this._y,this._iWidth,this._iHeight),this._oContainer.addChild(this._oDebugShape));this._oText=new createjs.Text(a,
this._iFontSize+"px "+this._szFont,this._szColor);this._oText.textBaseline="middle";this._oText.lineHeight=Math.round(this._iFontSize*this._fLineHeightFactor);this._oText.textAlign=this._szAlign;this._oText.lineWidth=this._bMultiline?this._iWidth-2*this._iPaddingH:null;switch(this._szAlign){case "center":this._oText.x=this._x+this._iWidth/2;break;case "left":this._oText.x=this._x+this._iPaddingH;break;case "right":this._oText.x=this._x+this._iWidth-this._iPaddingH}this._oContainer.addChild(this._oText);
this.refreshText(a)},setVerticalAlign:function(a){this._bVerticalAlign=a},setOutline:function(a){null!==this._oText&&(this._oText.outline=a)},setShadow:function(a,g,e,k){null!==this._oText&&(this._oText.shadow=new createjs.Shadow(a,g,e,k))},setColor:function(a){this._oText.color=a},setAlpha:function(a){this._oText.alpha=a},removeTweens:function(){createjs.Tween.removeTweens(this._oText)},getText:function(){return this._oText},getY:function(){return this._y},getFontSize:function(){return this._iFontSize},
refreshText:function(a){""===a&&(a=" ");null===this._oText&&this.__createText(a);this._oText.text=a;this._oText.font=this._iFontSize+"px "+this._szFont;this._oText.lineHeight=Math.round(this._iFontSize*this._fLineHeightFactor);this.__autofit();this.__updateY();this.__verticalAlign()}};
function CTLText(a,g,e,k,h,d,f,b,n,c,t,u,m,r,q,y,D){this._oContainer=a;this._x=g;this._y=e;this._iWidth=k;this._iHeight=h;this._bMultiline=y;this._iFontSize=d;this._szAlign=f;this._szColor=b;this._szFont=n;this._iPaddingH=t;this._iPaddingV=u;this._bVerticalAlign=q;this._bFitText=r;this._bDebug=D;this._oDebugShape=null;this._fLineHeightFactor=c;this._oText=null;m&&this.__createText(m)};